logicalclocks/feature-store-api

python/hsfs/engine/spark.py, python/setup.py
Closes #78
@moritzmeister - if you have a better place to locate this piece of code, let me know
=> Pydoop should handle hopsfs:// scheme

java/src/main/java/com/logicalclocks/hsfs/DataFormat.java, java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
```
val training_dataset = (fs.createTrainingDataset()
.name("sample_model")
.description("Dataset to train the sample model")
.version(1)
.dataFormat(DataFormat.TFRECORD)                       
.build())
training_dataset.insert(df,false)
```
=> [HOPSWORKS-1762] Add support for Spark-Tfrecord

java/src/main/java/com/logicalclocks/hsfs/HopsworksConnection.java, java/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksClient.java, java/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksExternalClient.java, java/src/test/java/com/logicalclocks/hsfs/TestHopsworksExternalClient.java, python/hsfs/client/__init__.py, python/hsfs/client/external.py, python/hsfs/connection.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1972
Python API Tested against:
https://colab.research.google.com/drive/1ZrOZzBLS4E0ue85sfRwISj5FlL2YiPfV?usp=sharing
Java API - new unit Test added in TestHopsworksExternalClient.java that needs an external cluster (but the unit test does not fail if external cluster not available).
=> [HOPSWORKS-1972] Featurestore connect using API key value

java/pom.xml, java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java, java/src/main/java/com/logicalclocks/hsfs/TrainingDataset.java, java/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupEngine.java, java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java, java/src/main/java/com/logicalclocks/hsfs/engine/StatisticsEngine.java, java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupApi.java, java/src/main/java/com/logicalclocks/hsfs/metadata/Statistics.java, java/src/main/java/com/logicalclocks/hsfs/metadata/StatisticsApi.java
Should be rebased either this or the python PR should be merged first and then the other one needs to be rebased.
=> [HOPSWORKS-1982] Deequ statistics for Feature Groups/Training Datasets

java/src/main/java/com/logicalclocks/hsfs/engine/TrainingDatasetEngine.java
never encountered this since I was always testing with a training dataset that was already created.
=> Training Dataset set Id from backend after creation

java/src/main/java/com/logicalclocks/hsfs/HopsworksConnection.java, java/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksClient.java, java/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksExternalClient.java, java/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksHttpClient.java, java/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksInternalClient.java, java/src/main/java/com/logicalclocks/hsfs/metadata/ProjectApi.java, java/src/test/java/com/logicalclocks/hsfs/TestHopsworksExternalClient.java, python/hsfs/client/external.py, python/hsfs/connection.py, python/hsfs/engine/spark.py
Also remove downloading of the certificates in the connect method for
PySpark clients. Certificates should already be present when the
application is started.
Closes #170
=> HSFS is defaulting to PyHive instead of Spark on EMR

java/src/main/java/com/logicalclocks/hsfs/StorageConnector.java, java/src/main/java/com/logicalclocks/hsfs/StorageConnectorType.java, java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java, java/src/main/java/com/logicalclocks/hsfs/metadata/StorageConnectorApi.java, java/src/main/java/com/logicalclocks/hsfs/util/Constants.java, python/hsfs/core/storage_connector_api.py, python/hsfs/engine/spark.py, python/hsfs/storage_connector.py, python/hsfs/training_dataset.py
logicalclocks/hops-testing-ee/pull/238
=> [HOPSWORKS-2085] redshift connector

docs/integrations/python.md, docs/integrations/sagemaker.md, python/hsfs/engine/__init__.py, python/setup.py
=> [HOPSWORKS-2206] HSFS profile to install with and without Hive dependencies

java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupBase.java, python/hsfs/feature_group.py
=> Select all Features of a Feature Group except few

java/src/main/java/com/logicalclocks/hsfs/StorageConnector.java, python/hsfs/storage_connector.py
We allow users to configure additional properties for their JDBC
storage connector to control performance, driver and so on.
These properties needs to be included in the spark_options method
(This was already fixed in https://github.com/logicalclocks/feature-store-api/pull/172 - but a bad merge rolled back the change)
=> JDBC connector spark_options should provide all the properties

utils/hsfs_utils.py
I had a case where the dict contains the field but with value `None` so the pop returns `None` instead of the default `{}`.
=> Fix ingestion job config dict with null value

python/hsfs/core/hudi_engine.py
The method was trying to update a dictionary with a set.
=> Fix typo in delete_record in hudi_engine

python/hsfs/engine/hive.py
Remove useSSL and allowPublicKeyRetrieval parameters when
connecting to the online feature store from a python environment
=> Fix Python online feature store connection

auto_doc.py, mkdocs.yml, python/hsfs/core/execution.py, python/hsfs/core/feature_group_engine.py, python/hsfs/core/job_api.py, python/hsfs/core/training_dataset_engine.py, python/hsfs/engine/hive.py, python/hsfs/feature_group.py, python/hsfs/training_dataset.py
* When calling save or insert on training datasets/feature groups
return the object to the user so that they can monitor the execution
* Add an option (wait_for_job, default True) to wait for the execution
to be finished before save or insert returns
* Update the documentation
=> Better Job handling for Hive engine

python/hsfs/engine/hive.py
`pd.read_parquet` apparently thinks that `obj['key']` is a file and calls open on it. This goes around that by reading the file first and then calling `read_parquet`
=> Fix reading Parquet external training dataset files

python/hsfs/core/feature_group_engine.py
When using the python engine, the validation should will be executed by the Hopsworks Job ingesting the data.
=> Fix validation for Python engine

python/hsfs/storage_connector.py, python/tests/test_storage_connector.py
- Handle the case in which the jdbc arguments are empty
- Add tests
=> Fix jdbc connector arguments split for no arguments

python/hsfs/core/tfdata_engine.py
Bug fix for tfdata listing files correctly. This PR is amendment for  https://github.com/logicalclocks/feature-store-api/issues/405
=> fix tfdata pattern glob if split is none

python/hsfs/engine/hive.py, python/hsfs/feature_group.py
In Spark 2.4 there was a change on the mode of reading a CSV file when, for some reason you cannot parse one of the columns. In particular:
In version 2.3 and earlier, CSV rows are considered as malformed if at least one column value in the row is malformed. CSV parser dropped such rows in the DROPMALFORMED mode or outputs an error in the FAILFAST mode. Since Spark 2.4, CSV row is considered as malformed only when it contains malformed column values requested from CSV datasource, other values can be ignored. As an example, CSV file contains the "id,name" header and one row "1234". In Spark 2.4, selection of the id column consists of a row with one column value 1234 but in Spark 2.3 and earlier it is empty in the DROPMALFORMED mode. To restore the previous behavior, set …
=> Add dropmalformed option when reading CSV for ingestion

python/hsfs/engine/hive.py, python/hsfs/feature_group.py
* Add dropmalformed option when reading CSV for ingestion
In Spark 2.4 there was a change on the mode of reading a CSV file when, for some reason you cannot parse one of the columns. In particular:
In version 2.3 and earlier, CSV rows are considered as malformed if at least one column value in the row is malformed. CSV parser dropped such rows in the DROPMALFORMED mode or outputs an error in the FAILFAST mode. Since Spark 2.4, CSV row is considered as malformed only when it contains malformed column values requested from CSV datasource, other values can be ignored. As an example, CSV file contains the "id,name" header and one row "1234". In Spark 2.4, selection of the id column consists of a row with one column value 1234 but in Spark 2.3 and earlier it is empty in the DROPMALFORMED mode. …
=> Add failfast option when reading CSV for ingestion (#428)

java/src/main/java/com/logicalclocks/hsfs/HopsworksConnection.java, python/hsfs/connection.py, python/hsfs/util.py
- `get_feature_store()` should require only the project name - the HSFS API should add `_featurestore` and lowercase the project name.
- we need to make it retrocompatible. As such, we should check if the user already provided the `_featurestore` part, and if so, not add it.
=> [HOPSWORKS-2948] Rewrite feature store name

python/hsfs/core/builtin_transformation_function.py, python/hsfs/core/transformation_function_engine.py, python/hsfs/feature_store.py
On Master we are removing the function entirely, on the 2.5 release we will add a deprecation note that it's not needed anymore.﻿
=> [HOPSWORKS-2918] Remove register builtin functions

python/hsfs/engine/python.py
According to kafka docs, the poll is cheap when there is nothing to do. So we can call it after every produce call. The producer batches the messages anyway.
=> [HOPSWORKS-3054][Append] Call poll in producer loop to empty callback queue

python/hsfs/training_dataset.py
"href" is removed from response after https://github.com/logicalclocks/hopsworks-ee/pull/951, this causes error in popping "href".
=> Fix training dataset init error

python/hsfs/engine/python.py
We are sending messages faster than librdkafka can get them delivered to kafka and the local queue is filling up.
Solution is to back off when this happens and retry the message where it happened. When the bufferError happens we can be sure that the message wasn't sent.
Adding hidden options: `debug_kafka` and `kafka_producer_config` for the future for debugging and to optimize producer loop.
https://github.com/confluentinc/confluent-kafka-python/issues/341#issuecomment-376067215
https://github.com/confluentinc/confluent-kafka-dotnet/issues/703
=> Handle BufferErrors by backing off and retrying

python/hsfs/core/feature_view_engine.py
Read event time from left feature group because query may not contain event time.
=> [HOPSWORKS-3201][append] set training dataset start end time

python/hsfs/core/training_dataset_engine.py
training datasets UI navigation has changed under Feature View. The link points to old UI  navigation so removing the prints.
=> HOPSWORKS-3210 remove printing training dataset old URL

python/hsfs/feature_group.py
The code wasn't using the proper setter which means that the
change was never updated in the backend
=> attach_expectation doesn't update validation type in the backend

java/src/main/java/com/logicalclocks/hsfs/engine/StatisticsEngine.java, python/hsfs/core/statistics_engine.py, python/hsfs/storage_connector.py
- change throwing warning instead of error while running statistics on empty dataframe
- add missing variable `JDBC_FORMAT` in RedshiftConnector
=> HOPSWORKS-3225 change throwing error to warning  while statistics on empty dataframe and add JDBC_FORMAT

.github/workflows/mkdocs-release.yml, docs/js/version-select.js
Adding the latest docs alias only to the mkdocs-release action so it will be correct for future released versions on new release branches.
=> Add latest docs alias to mkdocs-release action and hide major version alias in version select

python/hsfs/core/feature_view_engine.py
Currently, if `labels` has multiple entries, backend only take the last entry. This fixes it.
=> fix feature view features creation

java/pom.xml, python/hsfs/core/hudi_engine.py, python/hsfs/version.py
When we append a feature to a feature group, the new data being written
will have a different schema than the existing Parquet files.
The new files will have the additional column while the old Parquet
files will not.
This change make sure that the schemas of the different Parquet files is
merged to obtain the full schema with all the necessary features.
Keep in mind that in Hopsworks Feature Store we do not allow users to
remove columns from an existing feature group.
Also release 2.5.16
=> Set mergeSchema option to true to handle appended columns

python/hsfs/constructor/query.py, python/hsfs/feature_group.py
fixes quotes for code examples in docstring
=> [HOPSWORKS-3259][Append] Fix Docstrings for .as_of functions

java/src/main/java/com/logicalclocks/hsfs/FeatureView.java, java/src/main/java/com/logicalclocks/hsfs/engine/FeatureViewEngine.java, python/hsfs/core/feature_view_engine.py, python/hsfs/feature_view.py
changes:
1. Modified python and java client so that all splits' output are features first followed by labels.
2. Minor fix in `getBatchQuery`
=> [HOPSWORKS-3327] Reorder split output

python/hsfs/engine/python.py, python/tests/engine/test_python.py
- pass transformation function to `_apply_transformation_function` instead of training dataset object because the parameter has changed https://github.com/logicalclocks/feature-store-api/pull/707/commits/29d90121ea24173c7ecee1d465f5e932cd0e2620
JIRA Issue: -
Related PRs: -
```
```
=> [HOPSWORKS-3202][append] Fix parameter type mismatch

python/hsfs/constructor/query.py, python/hsfs/util.py, python/tests/constructor/test_query.py
This PR fixes query.as_of to allow wallclock_time=None
- includes unit tests
JIRA Issue: HOPSWORKS-3259
Priority for Review: medium
Related PRs: -
```
```
=> [HOPSWORKS-3259][append] Allow wallclocktime=None for as_of

python/hsfs/engine/python.py, python/tests/engine/test_python_writer.py, python/tests/fixtures/dataframe_fixtures.py
This PR fixed the timezone issue decribed in HOPSWORKS-3336
- This is to circumvent a bug/inconsistency in fastavro https://github.com/fastavro/fastavro/issues/642
- timestamps without tzinfo are handled as being in local timezone on linux and as being in UTC timezone on windows.
- to fix the issue, we explicitly set the timezone to utc if no tzinfo is specified.
JIRA Issue: https://hopsworks.atlassian.net/browse/HOPSWORKS-3336
Priority for Review: high
Related PRs: -
```
```
=> [HOPSWORKS-3336] Fix timezone issue

java/src/main/java/com/logicalclocks/hsfs/FeatureView.java, java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureViewApi.java, python/hsfs/core/feature_view_api.py, python/hsfs/feature_view.py
- Improve error message when getting a fv with deleted fg.
- Add `clean` method which allow users to delete fv without getting fv instance.
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-56] Enable cleaning of fv

utils/python/hsfs_utils.py
JIRA Issue: -
Related PRs: -
```
```
=> [HOPSWORKS-3337] add job to import data into feature group 

python/setup.py
adds a dependency for a plugin used in mkdocs in the documentation. It allows us to set variables and template links correctly with the right version without changing the links manually everywhere when releasing.
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-11
Related PRs: -
```
```
=> [FSTORE-11] Add mkdocs macros dependency for docs

python/hsfs/storage_connector.py
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-8] add query default argument in snowflake

python/hsfs/storage_connector.py
(cherry picked from commit 5585633977b7a8df04f60babea6693a5788362b5)
JIRA Issue: FSTORE-8
Related PRs: -
```
```
=> [FSTORE-8][3.0] add query default argument in snowflake

python/hsfs/connection.py
... adds a clearer description for the host parameter of the connection object.
JIRA Issue: FSTORE-33
Related PRs: -
```
```
=> [FSTORE-33] Improve HSFS parameter description

auto_doc.py, docs/templates/api/storage_connector_api.md, python/hsfs/constructor/query.py, python/hsfs/feature_group.py, python/hsfs/feature_view.py, python/hsfs/storage_connector.py, python/hsfs/training_dataset.py
adds the API docs for the Kafka Storage Connector.
JIRA Issue: FSTORE-345
Related PRs: -
```
```
=> [FSTORE-345] Update documentation to reflect supported methods in hsfs engines

docs/js/inject-api-links.js
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-348] Refactor Tutorials documentation page

python/hsfs/feature_view.py
... the api docs of feature view methods. 
JIRA Issue: FSTORE-383
Related PRs: -
```
```
=> [FSTORE-383] Feature View method documentation

python/hsfs/engine/spark.py, python/tests/engine/test_python_spark_convert_dataframe.py
This PR adds
- correct timezone-aware timestamp conversion in pySpark client non-UTC systems
JIRA Issue: FSTORE-311
Related PRs: -
```
```
=> [FSTORE-311][Append] Timezone-aware Timestamp conversion for PySpark client

python/hsfs/engine/spark.py, python/setup.py, python/tests/engine/test_python_spark_transformation_functions.py
This PR fixes datetime conversions for mixed timezones (e.g. timezones with DST)
JIRA Issue: FSTORE-311
Related PRs: -
```
```
=> [FSTORE-311][Append] Make Datetime Conversion DST-safe

java/src/main/java/com/logicalclocks/hsfs/StorageConnector.java, java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java, java/src/main/java/com/logicalclocks/hsfs/util/Constants.java, java/src/test/java/com/logicalclocks/hsfs/TestStorageConnector.java, python/hsfs/engine/spark.py, python/tests/engine/test_spark.py
- Fixes issue of key file not found authentication issue in case of multiple executors
JIRA Issue: -
https://hopsworks.atlassian.net/browse/FSTORE-392
Related PRs: -
```
```
=> [FSTORE-392] Change GCS authentication from key file path to account properties

python/hsfs/ge_expectation.py
Fix using unparsed meta object to the parse self.meta
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-423] Ensure meta is parsed before getting keys

python/setup.py
Pin gcsfs version to 2022.7.1
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-427] Fix fsspec version

python/hsfs/core/inode.py
Fix missing "type" from json
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-437] Fix inode init

keyFile.json, python/hsfs/core/great_expectation_engine.py, python/hsfs/core/validation_report_api.py, python/hsfs/core/validation_report_engine.py, python/hsfs/core/validation_result_api.py, python/hsfs/core/validation_result_engine.py, python/hsfs/feature_group.py, python/hsfs/ge_expectation.py, python/hsfs/ge_validation_result.py, python/hsfs/util.py, python/tests/core/test_validation_result_engine.py, python/tests/fixtures/expectation_suite_fixtures.json, python/tests/fixtures/feature_group_fixtures.json, python/tests/fixtures/ge_expectation_fixtures.json, python/tests/fixtures/ge_validation_result_fixtures.json, python/tests/fixtures/validation_report_fixtures.json, python/tests/test_feature_group.py, python/tests/test_util.py
This PR adds the possibility to query the validation history associated with an expectation by calling fg.get_validation_history(expectationId)
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-398] add validation history method to python client

.gitignore, java/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupUtils.java, java/src/main/java/com/logicalclocks/hsfs/engine/hudi/HudiEngine.java, python/hsfs/core/hudi_engine.py, python/tests/core/test_hudi_engine.py
Switching to connecting to the Hive Metastore instead of using the JDBC connection allows us to better handle certificates rotation. HiveServer2 through JDBC doesn't support application certificates, HMS does.
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-333] Hudi should use HMS hive sync instead of jdbc

python/hsfs/constructor/query.py, python/hsfs/core/feature_view_engine.py, python/hsfs/engine/python.py, python/hsfs/engine/spark.py, python/hsfs/feature_group.py, python/hsfs/feature_view.py
- revokes automatic type conversions for csv files (now that .parquet is default tds format, it is not essential)
- revokes automatic type conversions for reading sql / jdbc 
- adds flag to activate experimental type casting for fg.read() (read_options={"pandas_types":True})
- removed dependency between python and spark engine
- small fixes
JIRA Issue: FSTORE-526
Related PRs: https://github.com/logicalclocks/logicalclocks.github.io/pull/160, https://github.com/logicalclocks/loadtest/pull/37
```
```
=> [FSTORE-526] Made data type conversion an experimental feature

python/hsfs/storage_connector.py, python/tests/test_storage_connector.py
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-538] Redshift connector read throws validation error for query argument inspite of table name specified on connector

python/hsfs/core/expectation_suite_api.py, python/hsfs/core/expectation_suite_engine.py, python/hsfs/core/transformation_function_engine.py, python/hsfs/core/validation_report_api.py, python/hsfs/core/variable_api.py, python/hsfs/expectation_suite.py, python/hsfs/feature_group.py, python/hsfs/validation_report.py, python/tests/core/test_transformation_function_engine.py, python/tests/engine/test_spark.py
This PR also remove deprecated np.int, np.float and np.bool from TransformationFunctionEngine infer_spark_type
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-542][FSTORE-548] Enable python client 3.1 to app 3.0 compatibility for data validation api

java/pom.xml, python/hsfs/core/vector_server.py, python/hsfs/engine/python.py, python/hsfs/version.py, python/tests/engine/test_python.py, utils/java/pom.xml
the new sql alchemy version introduced new APIs, since the previous version was already forward compatible, we don't need to pin the version, but instead make hsfs work with both sqlalchemy 1.4.46 and 2.0.0 until pandas upgrades.
JIRA Issue: -
Related PRs: -
```
```
[FSTORE-555]: https://hopsworks.atlassian.net/browse/FSTORE-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FSTORE-556]: https://hopsworks.atlassian.net/browse/FSTORE-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FSTORE-589]: https://hopsworks.atlassian.net/browse/FSTORE-589?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
=> [3.1][FSTORE-639] Adjust for sqlalchemy 2.0.0

python/hsfs/engine/python.py, python/hsfs/engine/spark.py
- makes shallow copy of dataframe _before_ applying the timestamp conversion in python and spark engine
- use tzconvert(None)->tzlocalize(localtimezone) instead of tzconversion(localtimezone) in spark engine.
JIRA Issue: FSTORE-689
Related PRs: -
```
```
=> [FSTORE-689] Shallow dataframe copy hides TZ bug

python/hsfs/expectation_suite.py, python/hsfs/feature_group.py, python/hsfs/ge_expectation.py, python/tests/test_feature_group.py
Save expectation suite was failing with hopsworks object instead of GE object. Added unittest to ensure proper working, loadtest was also amended to go through the smart update code branch (both python and backend)
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-682] fix fg.save expectation suite

python/hsfs/ge_validation_result.py, python/tests/test_ge_validation_result.py
* Fix validation_time with timezone
* Convert to timestamp
* Add comment to clarify
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-693] fix validation time parsing with timezone cherry-pick

java/pom.xml, python/hsfs/version.py, python/setup.py, utils/java/pom.xml
- In pandas==2.0.0rc0, timestamp is treated as numerical value. This breaks the current statistics. 
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-758] Fix serialise timestamp

utils/java/src/main/java/com/logicalclocks/utils/MainClass.java, utils/python/hsfs_utils.py
Add start time to hsfs_util because scheduler will pass start time to job.
https://github.com/kennethmhc/hopsworks-ee/blob/871e5cfb22b59bb59e6079a2be070e8bb0e4639a/hopsworks-common/src/main/java/io/hops/hopsworks/common/jobs/JobScheduleV2Controller.java#L73
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-684] Add start time to hsfs_util

java/pom.xml, java/src/main/java/com/logicalclocks/hsfs/engine/hudi/DeltaStreamerKafkaSource.java, java/src/main/java/com/logicalclocks/hsfs/engine/hudi/HudiEngine.java, python/hsfs/engine/spark.py, python/hsfs/version.py, utils/java/pom.xml, utils/java/src/main/java/com/logicalclocks/utils/MainClass.java
- [FSTORE-782] Allow resetting kafka offsets for stream feature groups after backup/restore (#971)
- Release hsfs 3.1.1rc4
JIRA Issue: -
Related PRs: -
```
```
[FSTORE-782]: https://hopsworks.atlassian.net/browse/FSTORE-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FSTORE-782] Allow resetting kafka offsets for stream feature groups after backup/restore

python/hsfs/core/arrow_flight_client.py, python/tests/core/test_arrow_flight_client.py
This PR adds:
- support for datetime objects in flyingduck query filters
- support for unbinded features (i.e. `Feature("name")`)
JIRA Issue: FSTORE-854, FSTORE-853
Related PRs: -
```
```
=> [FSTORE-854] Accept datetime object in filter and support unbinded features

python/hsfs/engine/python.py, python/hsfs/util.py
This PR:
- adds an animated printout "Reading data with FlyingDuck..."/ "Reading data with Hive..." in python-only client
- prints "Finished ... (0.2s)" with runtime when finished
- removed printed query and warnings when querying with hive.
JIRA Issue: FSTORE-836
Related PRs: -
```
```
=> [FSTORE-836] Show "Reading data with..." message and remove Hive warning

python/hsfs/engine/python.py
This PR adds Pandas StringDtype support to schema check/conversion.
JIRA Issue: FSTORE-883
Related PRs: -
```
```
=> [FSTORE-883] Add Pandas StringDtype support

python/hsfs/constructor/join.py, python/tests/constructor/test_join.py, python/tests/fixtures/feature_view_fixtures.json, python/tests/fixtures/join_fixtures.json, python/tests/fixtures/query_fixtures.json, python/tests/test_feature_group_writer.py, python/tests/test_storage_connector.py
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-922] Python join deserialization reads join_type instead of type

python/hsfs/core/vector_server.py, python/hsfs/feature_view.py
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-1061] Add documentation for get_feature_vector and fallback to use raw feature name

python/hsfs/feature_group.py, python/tests/test_feature_group.py
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-916] FeatureGroup.insert does not retry in case of a failure

python/hsfs/constructor/query.py, python/hsfs/core/arrow_flight_client.py, python/hsfs/engine/python.py, python/hsfs/feature_group.py, python/hsfs/feature_view.py
This PR allows to configure the timeout for arrow flight which currently defaults to 30 seconds which is too short. The server has a queue timeout of 10 minutes which means the default should be longer than 10 minutes. Set it to 15 minutes and allow the user to configure it so that long running queries can be supported.
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1072
Related PRs: -
```
```
=> [FSTORE-1072] Configure timeout for arrow flight

python/hsfs/core/arrow_flight_client.py, python/setup.py
I cannot figure out why get_flight_info keeps failing in some scenarios. It appears like the request does in fact not reach our code. It's either an issue in the network stack, GRPC or ArrowFlight. The best I can do is adding retires which works around the issue.
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1087
Related PRs: -
```
```
=> [FSTORE-1087] Add retries for FlightUnavailableError

python/hsfs/client/auth.py
This PR adds a stripping of the authentication headers. 
- Analog to https://github.com/logicalclocks/hopsworks-api/pull/185, this PR changes the authentication header to strip the API key before handing it to the underlying HTTP library. This is simply due to the fact that if there is, for example, a trailing or a leading newline, the HTTP library performs a check on the validity of the header and sees that it is not valid (since newline characters are not allowed to be sent as part of the header) and therefore throws a ValueError, which prints the Invalid header value (in the tested case, the API key). 
- No changes have been made to user-facing APIs
JIRA Issue: -
Related PRs: https://github.com/logicalclocks/hopsworks-api/pull/185 …
=> added strip to authentication headers

python/hsfs/feature_view.py
This PR fixes the function recreate_training_data
- Correcting default value for write_options to an empty dictionary in recreate_training_data.
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-1110
Related PRs: -
```
```
=> [FSTORE-1110] Recreation of Training dataset throwing exception due to NULL reference

python/hsfs/engine/python.py
This PR fixes:
```
HTTP code: 400, HTTP reason: Bad Request, body: b'{"errorCode":270040,"usrMsg":", the provided feature name __index_level_0__ is invalid. Feature names can only contain lower case characters, numbers and underscores, have to start with a letter and cannot be longer than 63 characters or empty."
```
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-1118][APPEND] Disable preserve_index for pyarrow from_pandas

python/hsfs/storage_connector.py, python/tests/fixtures/storage_connector_fixtures.json, python/tests/test_storage_connector.py
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-1184] Kafka storage connector confluent_options method uses wrong certificates

python/hsfs/constructor/query.py, python/hsfs/feature_group.py
Documentation for the filter has been expended by adding a reminder that logical operands must be used with symbols and not in written form
=> [FSTORE-1074] Expand documentation on filter logic

CONTRIBUTING.md
In the instruction to build the documentation (`Contriburing.md`) the following command does not work:
`pip install -e .[python,dev,docs]`
The working command is:
`pip install -e ".[python,dev,docs]"`
2. The Python version should not be higher than 3.9. Otherwise, the following command will fail due to library conflicts:
`python auto_doc.py`
=> [FSTORE-1222] Fix Feature Store API Contriburing.md instructions

python/hsfs/constructor/query.py, python/hsfs/feature_group.py
Added banner in as_of and read_changes about the fact that the methods are not available in Python, but only in Spark.
=> [FSTORE-1218] Fix as_of and read_changes doc

python/hsfs/core/feature_view_engine.py
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-1181][APPEND] for materialized training datasets check helper column name clashes only on creation phase

python/hsfs/core/feature_monitoring_result_engine.py, python/hsfs/engine/python.py
This PR fixes the issue in which creation of training test split without materialization feailing when during computing statistics when Feature Group contains certain date time types.
**Changes Done**
- Used pyarrow schema to compare type instead of using pandas types. This is done because pandas has multiple type classes that represent a single data type while `pyarrow.Schema.from_pandas` does the mapping and converts it to a single pyarrow type making it easier for type checking. 
- Added support to check all possible types and map them to corresponding datatypes.
JIRA Issue: - https://hopsworks.atlassian.net/browse/FSTORE-1253
Related PRs: -
```
```
=> [FSTORE-1253] Adding support for all datatype during statistic computation

python/hsfs/embedding.py
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-1260] Hsfs should not use hsml client to get embedding model

java/beam/pom.xml, java/flink/pom.xml, java/hsfs/pom.xml, java/pom.xml, java/spark/pom.xml, python/hsfs/client/exceptions.py, python/hsfs/core/external_feature_group_engine.py, python/hsfs/core/feature_group_engine.py, python/hsfs/feature_group.py, python/hsfs/util.py, python/hsfs/version.py, python/tests/core/test_feature_group_engine.py, python/tests/test_util.py, utils/java/pom.xml
…a dataframe if the validation ingestion policy is set to strict (#1226)
* Add DataValidationException class
* Raise DataValidationException on validation failure if validation ignestion policy set to strict
* Fix associated unit test
* Append to insert documentation
* Raise exception also when inserting only in the online Feature Store for External FG
* Add documentation to insert for External FG
* Refactor get_feature_group_url and improve DataValidationException message
* Remove pytest bigquery.json
---------
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-1247] Raise DataValidationError on validation failure if ingestion set to strict

python/hsfs/core/arrow_flight_client.py, python/hsfs/core/feature_view_engine.py, python/hsfs/core/vector_server.py, python/hsfs/engine/python.py, python/hsfs/engine/spark.py, python/hsfs/feature_group.py, python/hsfs/feature_store.py, python/hsfs/feature_view.py, python/hsfs/storage_connector.py, python/setup.py, python/tests/core/test_feature_view_engine.py, python/tests/engine/test_python.py, python/tests/engine/test_spark.py
This PR adds support for Polars, specifically writing  and reading polars dataframes to a feature store.
**Changes:**
1. **Write Support for Polars**
- Added support for pyarrow types : large_list, large_string and large_binary - Since lists, string and binary types are converted into large_list, large_string and large_binary formats when a polars dataframe is created from a pandas dataframe.
- Also added support for pyarrow dictionary types that has value_type which can be any strings type and index_type that can be any integer type. This done because category types are in Polars are represented as a dictionary value_type string and index_type integer
- Modified function for convert_to_default_dataframe, _write_dataframe_kafka and parse_schema_feature_group to perform same functionality …
=> [FSTORE-1186] Polars Integration into Hopsworks - Writing and Reading DataFrames 

python/hsfs/core/arrow_flight_client.py, python/hsfs/core/vector_server.py, python/hsfs/engine/python.py, python/hsfs/engine/spark.py, python/tests/engine/test_python.py
This PR fixes two issue present in the integration of Polars to Hopsworks
1. **Helper Columns** - When reading helper columns as a polars dataframe incorrect columns with empty data was obatined.
- _Root Cause_: Issue caused due to incorrect schema being used to create the polars dataframe. Polars dataframe was created using schema extracted from feature vectors.
- _Fix done_ : Corrected the schema used by extracting the inference helper columns.
3. **Training Data** - When creating training data from a feature group with very little data, an exception is encountered sporadically.
- _Root Cause_ : Issue caused due to the very little data being available in the feature group. When very little training data is present in the feature group there is a possibility that one of the training data …
=> [FSTORE-1186][APPEND] Polars Integration into Hopsworks - Writing and Reading DataFrames

python/hsfs/constructor/query.py
I will add a corresponding test in integration tests.
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-1316] Catch early failure to read from online storage via query.read if not all FG are online enabled

python/hsfs/constructor/query.py, python/hsfs/feature_group.py
The backend raises an error if you provide a number to read as it is interpreted as wallclock time but we don't check for
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-1316][APPEND] Move check read supported and check earlier for as_of being used in python client

python/hsfs/__init__.py, python/setup.py
- This PR suppresses the CPU check warning printed while importing hsfs. These warnings are suppressed since they are largely false positives.
- The version of polars is also pinned to the last stable release polars has very high frequency releases.
JIRA Issue: - https://hopsworks.atlassian.net/browse/FSTORE-1334?atlOrigin=eyJpIjoiY2FiZGU2MzM1ZWIzNGYwZGI1ZTNhOGRlMGM2OGY5NDMiLCJwIjoiaiJ9
```
```
=> [FSTORE-1334] Pin Polars Version and supress polars CPU warning

python/hsfs/core/feature_descriptive_statistics.py, python/hsfs/core/feature_group_base_engine.py, python/hsfs/core/feature_monitoring_config.py, python/hsfs/core/monitoring_window_config.py, python/hsfs/core/monitoring_window_config_engine.py, python/hsfs/core/statistics_engine.py, python/hsfs/core/validation_result_engine.py, python/hsfs/engine/python.py, python/hsfs/engine/spark.py, python/hsfs/feature.py, python/hsfs/feature_group.py, python/hsfs/feature_view.py, python/hsfs/statistics.py, python/hsfs/statistics_config.py, python/hsfs/storage_connector.py, python/hsfs/training_dataset.py, python/hsfs/training_dataset_feature.py, python/hsfs/transformation_function.py, python/hsfs/util.py, python/tests/core/test_feature_group_engine.py, python/tests/engine/test_python.py, python/tests/engine/test_spark.py, python/tests/fixtures/dataframe_fixtures.py, python/tests/test_feature.py, python/tests/test_feature_group.py
Cherry-pick lead to circular import which lead to lots of file being touched but not really affected
*Autofix feature names which contains spaces
* Update python/hsfs/engine/python.py
* Update python/hsfs/engine/python.py
* Update python/hsfs/engine/spark.py
* Update python/hsfs/engine/spark.py
* Code review
* Fix error messages in unit tests
---------
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-1330] Autofix feature names which contains spaces (#1292)

python/hsfs/core/opensearch.py, python/tests/core/test_opensearch.py
In opensearch-py client before 2.3, it requires timeout parameter to be a string with unit.
`opensearchpy.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'failed to parse setting [timeout] with value [30] as a time value: unit is missing or unrecognized')`
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-1317] Hanlde opensearch timeout parameter

python/hsfs/engine/python.py, python/tests/engine/test_python.py
This is meant to allow for concurrent execution of materialization jobs. If offset is not explicitly stated then it is received from kafka and another job might have committed new one right before the concurrently running job has received it.
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-1402][APPEND] Always provide offsets for the first execution of materialization job

python/hsfs/util.py
Utils changes were removed in previous so adding them back.
JIRA Issue: -
Related PRs: -
```
```
=> [FSTORE-1382] undo conflicted overwritten method

python/hsfs/client/external.py
`enableHiveSupport` on itself is a method, and has to be called to get a builder from it.
JIRA Issue: [FSTORE-1459](https://hopsworks.atlassian.net/browse/FSTORE-1459)
Related PRs: -
```
```
[FSTORE-1459]: https://hopsworks.atlassian.net/browse/FSTORE-1459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FSTORE-1459] Fix spark initialization in client/external.py

python/tests/client/test_base_client.py, python/tests/util.py
It was impure, changing environ variable and thereby messing other tests (for example, [test_login.py](https://github.com/logicalclocks/hopsworks-api/blob/main/python/tests/hopsworks/test_login.py) from hopsworks-api). This PR wraps the tests from this file in a decorator saving and restoring os.environ.
JIRA Issue: [FSTORE-1459](https://hopsworks.atlassian.net/browse/FSTORE-1459)
Related PRs: -
```
```
[FSTORE-1459]: https://hopsworks.atlassian.net/browse/FSTORE-1459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FSTORE-1459] Fix test_base_client.py

java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/SparkEngine.java, python/hsfs/feature_view.py, utils/java/src/main/java/com/logicalclocks/utils/MainClass.java, utils/python/hsfs_utils.py
JIRA Issue: -
Related PRs: -
```
```
=> [HWORKS-1416] Close sparks sessions
