logicalclocks/feature-store-api

python/hsfs/core/feature_group_engine.py
python/hsfs/core/query.py
python/hsfs/engine/spark.py
python/hsfs/feature_group.py

default storage is not set on feature group creation

---

python/hsfs/feature.py
python/hsfs/feature_group.py

Python client ignore partition_key in feature group

---

java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
python/hsfs/feature_group.py

Don't allow to specify storage on save

---

python/hsfs/client/base.py

Python client can't handle empty responses from the backend

---

java/src/main/java/com/logicalclocks/hsfs/HopsworksConnection.java
python/hsfs/connection.py

Lowercase feature store name before calling the get

---

python/hsfs/engine/spark.py

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1762

[HOPSWORKS-1762] Add support for Spark-Tfrecord

---

java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
java/src/main/java/com/logicalclocks/hsfs/TrainingDataset.java

Fixes two minor things:
1. Setting the default for statistics to true
2. Add JsonIgnore to getStatistics methods of training dataset

Java API Fixes

---

java/pom.xml
java/src/main/java/com/logicalclocks/hsfs/Feature.java
java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
java/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupEngine.java
java/src/main/java/com/logicalclocks/hsfs/engine/Utils.java
java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupApi.java

usage:
```scala
var houses_sold = fs.getFeatureGroup("houses_sold", 1)
val l = Seq(new Feature("asdgadfg", "double", "5.0"))
houses_sold.appendFeatures(l)
```
or
```scala
houses_sold.appendFeatures(new Feature("asdgadfg", "double", "5.0"))
```

[HOPSWORKS-2009] Append Features to Feature Group schema

---

java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
java/src/main/java/com/logicalclocks/hsfs/MainClass.java
java/src/main/java/com/logicalclocks/hsfs/Storage.java
java/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupEngine.java
java/src/main/java/com/logicalclocks/hsfs/engine/StatisticsEngine.java
java/src/main/java/com/logicalclocks/hsfs/metadata/Query.java

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2084

[HOPSWORKS-2084] Remove default_storage option from feature groups

---

java/src/main/java/com/logicalclocks/hsfs/Feature.java
java/src/main/java/com/logicalclocks/hsfs/engine/Utils.java

Don't set spark type as online type in Java API

---

java/src/main/java/com/logicalclocks/hsfs/StorageConnector.java
python/hsfs/storage_connector.py

Extend setup of JDBC storage connectors to allow for additional
parameters. Mainly isolationLevel and batchsize used to tweak writing to
the online feature store

Account for other configuration parameters

---

python/hsfs/feature.py

Add online type getter/setter to Feature

---

docs/templates/feature.md

[HOPSWORKS-2277] Add feature type docs

---

java/src/main/java/com/logicalclocks/hsfs/Feature.java
java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
java/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupEngine.java
java/src/main/java/com/logicalclocks/hsfs/engine/HudiEngine.java
python/hsfs/core/feature_group_engine.py
python/hsfs/core/hudi_engine.py
python/hsfs/feature.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py

also includes https://logicalclocks.atlassian.net/browse/HOPSWORKS-2196

[HOPSWORKS-2188] Remove partition key requirements for HUDI feature groups and allow users to set precombine keys

---

Dockerfile
Jenkinsfile_doc
docs/css/version-select.css
docs/js/version-select.js
mkdocs.yml
python/setup.py

The CSS and JS file will need to be added to the old release branches, too, before building them.

Documentation version selector

---

java/src/main/java/com/logicalclocks/hsfs/TrainingDataset.java
java/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupBaseEngine.java
java/src/main/java/com/logicalclocks/hsfs/engine/TrainingDatasetEngine.java
java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupBase.java
java/src/main/java/com/logicalclocks/hsfs/metadata/TagsApi.java
java/src/test/java/com/logicalclocks/hsfs/metadata/TestTagsApi.java
python/hsfs/core/feature_group_base_engine.py
python/hsfs/core/tags_api.py
python/hsfs/core/training_dataset_engine.py
python/hsfs/feature_group.py
python/hsfs/tag.py
python/hsfs/training_dataset.py

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1978

[HOPSWORKS-1978] schematized tags

---

java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
python/hsfs/feature_group.py

Throw error when using Hudi specific methods on non Hudi feature groups

---

docs/css/custom.css
docs/hopsworksai/index.md
mkdocs.yml

Co-authored-by: Moritz Meister <8422705+moritzmeister@users.noreply.github.com>

add landing page for hopsworks ai and reorganize sections

---

java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java

Fixes NullPointerException if primary and partition keys were not provided

ifNotNullPPK

---

java/pom.xml
java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
java/src/main/java/com/logicalclocks/hsfs/engine/Utils.java
java/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksClient.java
java/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksExternalClient.java
java/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksHttpClient.java
java/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksInternalClient.java
python/hsfs/client/external.py
python/hsfs/client/hopsworks.py
python/hsfs/core/hudi_engine.py
python/hsfs/util.py
python/hsfs/version.py

Fix Hudi Cert Key issue External Clients

---

java/src/main/java/com/logicalclocks/hsfs/TrainingDataset.java
java/src/main/java/com/logicalclocks/hsfs/engine/TrainingDatasetEngine.java
java/src/main/java/com/logicalclocks/hsfs/metadata/TrainingDatasetApi.java
python/hsfs/core/training_dataset_api.py
python/hsfs/training_dataset.py

[HOPSWORKS-2502] Add training dataset delete

---

docs/hopsworksai/aws/instance_profile_permissions.md
docs/hopsworksai/aws/restrictive_permissions.md
docs/hopsworksai/aws/upgrade.md
docs/hopsworksai/azure/getting_started.md
docs/hopsworksai/azure/restrictive_permissions.md
docs/hopsworksai/azure/upgrade.md

* Fixes for upgrade documentation
* Update docs/hopsworksai/aws/restrictive_permissions.md
Co-authored-by: Gautier Berthou <gautier@logicalclocks.com>
* Update docs/hopsworksai/aws/restrictive_permissions.md
Co-authored-by: Gautier Berthou <gautier@logicalclocks.com>
* Update docs/hopsworksai/azure/restrictive_permissions.md
Co-authored-by: Gautier Berthou <gautier@logicalclocks.com>
* fixes for review
Co-authored-by: Gautier Berthou <gautier@logicalclocks.com>

Fixes for upgrade documentation (#351)

---

auto_doc.py
docs/templates/on_demand_feature_group.md
mkdocs.yml

Add on-demand feature groups documentation

---

python/hsfs/engine/spark.py
python/hsfs/feature_group.py

Handle correctly Delta, Parquet, ORC file formats on on-demand feature

---

utils/hsfs_utils.py

To avoid type missmatch (eg. long handled as int) we need to use
the feature group data to read the csv file with the data being
ingested into the feature group.

Use feature group schema to read the csv ingested fg data

---

java/src/main/java/com/logicalclocks/hsfs/engine/HudiEngine.java
python/hsfs/core/hudi_engine.py

Only drops duplicates for Insert operations such as Insert and Bulk Insert.

Hudi drop duplicate records on bulk insert

---

python/hsfs/core/tfdata_engine.py
python/hsfs/training_dataset.py

This PR fixes issue https://github.com/logicalclocks/feature-store-api/issues/405

[HOPSWORKS-2664] Fix tfdata engine when interleave is enabled 

---

python/hsfs/core/transformation_function_engine.py
python/hsfs/engine/spark.py

Allow transformation functions to produce new, transformed column when creating training dataset

[HOPSWORKS-2690] Allow transformation functions to produce transformed columns

---

python/hsfs/core/transformation_function_engine.py
python/hsfs/engine/spark.py

Reverts logicalclocks/feature-store-api#416

Revert [HOPSWORKS-2690] Allow transformation functions to produce transformed columns

---

utils/hsfs_utils.py

Hsfs utils manual schema construction

---

utils/hsfs_utils.py

Hsfs utils manual schema construction (#419)

---

java/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupEngine.java
java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
python/hsfs/engine/spark.py

This reverts commit 35d77cd2b50b9169fbffccdfe3b8bc3bf0872e5c.

Revert "allow users to set checkpoint location"

---

docs/hopsworksai/aws/getting_started.md
docs/hopsworksai/azure/getting_started.md
docs/hopsworksai/services.md
docs/integrations/databricks/networking.md
docs/integrations/emr/networking.md
docs/integrations/python.md
mkdocs.yml

Fixes https://github.com/logicalclocks/hopsworks-cloud/issues/2218

[HOPSWORKS-CLOUD-2218] small services documentation for hopsworksai

---

java/src/main/java/com/logicalclocks/hsfs/FeatureStore.java
java/src/main/java/com/logicalclocks/hsfs/StorageConnector.java
java/src/main/java/com/logicalclocks/hsfs/constructor/Query.java
java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
python/hsfs/client/external.py

This reverts commit d0a9c674ec11ec61eff7442887bae576edade51f.

Revert "Validate Spark configuration when calling connect() (#430)"

---

python/hsfs/constructor/filter.py
python/hsfs/constructor/query.py
python/hsfs/feature.py

This is used when rebuilding the query with filters from a JSON object
when using the UI or the Python API to generate a training dataset

Add method to rebuild query logic/filter options from a json object

---

java/src/main/java/com/logicalclocks/hsfs/TrainingDataset.java
java/src/main/java/com/logicalclocks/hsfs/engine/TrainingDatasetEngine.java
python/hsfs/core/training_dataset_engine.py
python/hsfs/training_dataset.py

It reads the wrong directory and it complains it can't find the schema

Reading non-split parquet training dataset fails

---

python/hsfs/feature_group.py

accidentally removed this line in #328

[HOPSWORKS-2504][Fix Append] Add back location attribtue to FeatureGroupBase

---

java/src/main/java/com/logicalclocks/hsfs/TrainingDataset.java
java/src/main/java/com/logicalclocks/hsfs/engine/TrainingDatasetEngine.java
java/src/main/java/com/logicalclocks/hsfs/metadata/TrainingDatasetApi.java
python/hsfs/core/training_dataset_api.py
python/hsfs/core/training_dataset_engine.py
python/hsfs/training_dataset.py

resolve #523 
1. Add "hive query" parameter to java and python client.

[HOPSWORKS-2838] Training dataset get_query for offline storage not working on hive engine

---

java/pom.xml
python/hsfs/version.py

- Bump Deequ version to 1.1.0.4-SNAPSHOT
- Release version 2.4.7

Bump deequ version to 1.1.0.4-SNAPSHOT and release hsfs 2.4.7

---

java/src/main/java/com/logicalclocks/hsfs/engine/DataValidationEngine.java
java/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupEngine.java
java/src/main/java/com/logicalclocks/hsfs/engine/OnDemandFeatureGroupEngine.java
java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupBase.java
java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupValidations.java
java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupValidationsApi.java
python/hsfs/core/data_validation_engine.py
python/hsfs/core/feature_group_engine.py
python/hsfs/engine/spark.py
python/hsfs/feature_group.py
python/hsfs/feature_group_validation.py

Do not log calls to fg.validate(df) as a feature store activity

[HOPSWORKS-2850] Fine-grained activity logging for validations

---

java/src/main/java/com/logicalclocks/hsfs/Feature.java

Serialise the feature object as feature value for feature comparison.

[HOPSWORKS-2819] allow feature comparison in query filters

---

java/pom.xml
python/hsfs/core/feature_group_engine.py
python/hsfs/core/training_dataset_engine.py
python/hsfs/engine/hive.py
python/hsfs/training_dataset.py
python/hsfs/util.py
python/hsfs/version.py

- Add MySQL connection pool for fs.sql and get_serving_vector (#463)
- Release hsfs version 2.2.22

[2.2] Cherry-pick online feature store connection pool

---

python/hsfs/training_dataset.py

Add comment about saving of filter

[HOPSWORKS-2855] Add comment about saving of filter

---

python/hsfs/core/dataset_api.py

Removes one of the copies of the data in memory

[HOPSWORKS-2933] Improve HSFS Python upload memory usage

---

java/src/main/java/com/logicalclocks/hsfs/StorageConnector.java
java/src/main/java/com/logicalclocks/hsfs/engine/TrainingDatasetEngine.java
python/hsfs/core/training_dataset_engine.py
python/hsfs/storage_connector.py

resolve https://github.com/logicalclocks/feature-store-api/issues/544
Changes:
1. Update online storage connector before read
2. Setup new mysql connection when connection failed in `get_serving_vector`

[Hopsworks-2919] Refresh online storage connector

---

java/pom.xml
java/src/main/java/com/logicalclocks/hsfs/StorageConnector.java
java/src/main/java/com/logicalclocks/hsfs/engine/TrainingDatasetEngine.java
python/hsfs/core/training_dataset_engine.py
python/hsfs/storage_connector.py
python/hsfs/version.py

[V2.4][HOPSWORKS-2919] Refresh online storage

---

python/hsfs/engine/hive.py
python/hsfs/util.py

Prevent side effect on pandas dataframe column names

---

python/hsfs/engine/hive.py

[HOPSWORKS-2999] HSFS Hive engine should throw proper errors for all unsupported methods

---

.github/workflows/mkdocs-master.yml
.github/workflows/mkdocs-release.yml
CONTRIBUTING.md
docs/CONTRIBUTING.md
docs/integrations/mlstudio_designer.md
docs/integrations/mlstudio_notebooks.md
docs/integrations/python.md
docs/integrations/sagemaker.md
docs/integrations/spark.md
python/hsfs/client/external.py
python/hsfs/connection.py
python/hsfs/constructor/query.py
python/hsfs/core/feature_group_engine.py
python/hsfs/core/statistics_engine.py
python/hsfs/engine/__init__.py
python/hsfs/engine/python.py
python/hsfs/engine/spark.py
python/hsfs/feature_group.py
python/hsfs/storage_connector.py
python/hsfs/training_dataset.py
python/setup.py

[HOPSWORKS-3051] Add new Python extra to HSFS for python engine to replace hive

---

auto_doc.py
docs/templates/api/storage_connector_api.md
docs/templates/storage_connector.md
java/src/main/java/com/logicalclocks/hsfs/FeatureStore.java
java/src/main/java/com/logicalclocks/hsfs/StorageConnector.java
java/src/main/java/com/logicalclocks/hsfs/StorageConnectorType.java
java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
java/src/main/java/com/logicalclocks/hsfs/util/Constants.java
python/hsfs/engine/spark.py
python/hsfs/storage_connector.py

Changes to add GCS storage connector

[HOPSWORKS-2890] Add GCS connector

---

java/pom.xml

Bump Deequ version to 1.1.0.5-SNAPSHOT

---

auto_doc.py
docs/templates/api/storage_connector_api.md
docs/templates/storage_connector.md
java/src/main/java/com/logicalclocks/hsfs/FeatureStore.java
java/src/main/java/com/logicalclocks/hsfs/StorageConnector.java
java/src/main/java/com/logicalclocks/hsfs/StorageConnectorType.java
java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
java/src/main/java/com/logicalclocks/hsfs/util/Constants.java
python/hsfs/engine/spark.py
python/hsfs/storage_connector.py

[HOPSWORKS-3010] add bigquery connector

---

java/src/main/java/com/logicalclocks/hsfs/FeatureView.java
java/src/main/java/com/logicalclocks/hsfs/TrainingDatasetFeature.java
java/src/main/java/com/logicalclocks/hsfs/engine/FeatureViewEngine.java
java/src/main/java/com/logicalclocks/hsfs/engine/VectorServer.java
java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureViewApi.java
python/hsfs/core/vector_server.py

Changes:
1. Implement feature serving (getFeatureVector and perviewFeatureVector) in Java client.
2. Minor fix of `init_serving` in Python client.

[HOPSWORKS-3099] Feature view serving java client

---

java/src/main/java/com/logicalclocks/hsfs/engine/FeatureViewEngine.java
java/src/main/java/com/logicalclocks/hsfs/metadata/TagsApi.java
python/hsfs/core/tags_api.py

Changes:
1. Add tags related methods for feature view and training dataset in java client.

[HOPSWORKS-3099] Feature view tags for java client

---

java/pom.xml

Related to https://github.com/logicalclocks/hudi/pull/18

Bump hudi to 0.10.0.2

---

java/src/main/java/com/logicalclocks/hsfs/FeatureView.java
java/src/main/java/com/logicalclocks/hsfs/TrainingDataset.java
java/src/main/java/com/logicalclocks/hsfs/engine/FeatureViewEngine.java
python/hsfs/core/feature_view_engine.py
python/hsfs/feature_view.py
python/hsfs/training_dataset.py

changes in this PR:
rename:
1. createTrainValidationTestSplits -> createTrainValidationTestSplit
2. val* -> validation*

[FeatureView] Rename methods and variables of feature view

---

java/pom.xml

Related to https://github.com/logicalclocks/spark/pull/31

[HOPSWORKS-3233] Bump spark to 3.1.1.3

---

python/hsfs/engine/python.py
python/hsfs/engine/spark.py

@o-alex 
made `time_travel_format` optional

[HOPSWORKS-3261] Fix saving external feature group

---

docs/js/inject-api-links.js

(cherry picked from commit 320f4bf368b53483a6112bebb5707b8f67fabe85)

Adjust links for updated tutorials structure

---

python/hsfs/validation_report.py

- Add ge validate util job
- fix attribute in repr

Fix atttribute access in validation report repr

---

java/pom.xml
python/hsfs/core/feature_view_engine.py
python/hsfs/validation_report.py
python/hsfs/version.py

PR should be merged before releasing hsfs 3.0.1
(cherry picked from commit 4f7f87c026d38bc64714cd04bdb1228342c0c093)

Cherry-picked bug fix commits for hsfs 3.0.1

---

java/src/main/java/com/logicalclocks/hsfs/FeatureView.java
java/src/main/java/com/logicalclocks/hsfs/TrainingDataset.java
java/src/main/java/com/logicalclocks/hsfs/constructor/Filter.java
java/src/main/java/com/logicalclocks/hsfs/constructor/FilterLogic.java
java/src/main/java/com/logicalclocks/hsfs/engine/FeatureViewEngine.java
java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureViewApi.java
python/hsfs/core/feature_view_api.py
python/hsfs/core/feature_view_engine.py
python/hsfs/core/statistics_engine.py
python/hsfs/engine/python.py
python/hsfs/engine/spark.py
python/hsfs/feature_view.py
python/hsfs/training_dataset.py
python/tests/core/test_feature_view_engine.py
python/tests/engine/test_python.py
python/tests/engine/test_spark.py
python/tests/fixtures/training_dataset_fixtures.json

changes:
1. Fix query parameter in feature view API
2. Add extra filter to all get/create TD
3. Add td version to get batch query/data.
4. Add extra filter to td entity.
5. Remove default td version = 1 when init batch scoring since backend will not be able to fetch if there is none.

[HOPSWORKS-3202] Add filter to td

---

3.0.0/js/version-select.js
3.0.1/js/version-select.js
3.0.2/js/version-select.js

JIRA Issue: -
Related PRs: -
```
```

Selecting a different version dropdown for 3.X series should land on correct page

---

docs/js/version-select.js

JIRA Issue: -
Related PRs: -
```
```

Selecting a different version dropdown should land on correct page

---

python/hsfs/engine/spark.py
python/tests/engine/test_spark.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-53] apply_transformation_function provided Training Dataset instead of Transformation Functions

---

python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-56][APPEND] Check parameter type

---

python/setup.py
python/tests/engine/test_spark.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-315] Upgrading GE version to 0.14.12 to support Jinja2 version 3.0.0

---

utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Fix hsfs utils java version

---

java/pom.xml
java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
python/hsfs/engine/spark.py
python/hsfs/version.py

- remove refetch
- Release version 2.5.17
JIRA Issue: -
Related PRs: -
```
```

[HOPSWORKS-3296][2.5] Remove update of storage connector

---

java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
python/hsfs/engine/spark.py

JIRA Issue: -
Related PRs: -
```
```

[HOPSWORKS-3296][3.0] Remove update of storage connector

---

java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
python/hsfs/engine/spark.py

JIRA Issue: -
Related PRs: -
```
```

[HOPSWORKS-3296] Remove update of storage connector

---

java/pom.xml
java/src/main/java/com/logicalclocks/hsfs/StorageConnector.java
java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
java/src/test/java/com/logicalclocks/hsfs/TestStorageConnector.java

- Add java part fix
- add one more assertion
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-8][append] Java fix for snowflake connector

---

auto_doc.py
docs/templates/api/storage_connector_api.md
python/hsfs/constructor/query.py
python/hsfs/feature_group.py
python/hsfs/feature_view.py
python/hsfs/storage_connector.py
python/hsfs/training_dataset.py

(cherry picked from commit 05c1481c67280b3b72c36199c1e7fc8f6630a85c)
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-345] Update documentation to reflect supported methods in hsfs engines

---

java/src/main/java/com/logicalclocks/hsfs/engine/FeatureViewEngine.java
python/hsfs/core/feature_view_engine.py

Changes:
1. Catch error code 270172 and throw more detailed error message.
2. Refactor conversion of event time.
3. Add `convert_event_time_to_timestamp` to `get_batch_query`.
JIRA Issue: -
Related PRs: -
```
```

[HOPSWORKS-3345] Improve event time error message

---

docs/js/inject-api-links.js

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-348][3.0] Refactor Tutorials documentation page

---

java/src/main/java/com/logicalclocks/hsfs/engine/FeatureViewEngine.java

fix style
JIRA Issue: -
Related PRs: -
```
```

[HOPSWORKS-3345][APPEND] Improve event time error message

---

mkdocs.yml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-358] Add icon to external links in documentation navigation

---

.github/workflows/java-ut.yml
java/src/main/java/com/logicalclocks/hsfs/engine/FeatureViewEngine.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-342] Add java tests to github pipeline

---

java/src/main/java/com/logicalclocks/hsfs/FeatureView.java
java/src/main/java/com/logicalclocks/hsfs/constructor/Query.java
python/hsfs/constructor/query.py
python/hsfs/core/feature_view_engine.py
python/hsfs/engine/python.py
python/hsfs/feature_store.py
python/tests/core/test_feature_view_engine.py
python/tests/core/test_statistics_engine.py
python/tests/engine/test_python.py
python/tests/engine/test_spark.py

- Show warning when there is `as_of` in the query when creating a feature view
- Raise exception when reading incremental query from python engine
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-346] Handle as_of in feature view

---

utils/python/hsfs_utils.py

JIRA Issue: -
Related PRs: -
```
```

[HOPSWORKS-3337] add job to import data into feature group  (#774)

---

python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-383][3.0] Feature View method documentation

---

auto_doc.py
docs/templates/api/expectation_suite_api.md
docs/templates/api/validation_report_api.md
mkdocs.yml
python/hsfs/core/expectation_api.py
python/hsfs/core/expectation_engine.py
python/hsfs/core/expectation_suite_api.py
python/hsfs/core/expectation_suite_engine.py
python/hsfs/core/feature_group_engine.py
python/hsfs/core/great_expectation_engine.py
python/hsfs/core/validation_report_api.py
python/hsfs/core/validation_report_engine.py
python/hsfs/expectation_suite.py
python/hsfs/feature_group.py
python/hsfs/ge_expectation.py
python/tests/core/test_expectation_engine.py
python/tests/core/test_expectation_suite_engine.py
python/tests/core/test_feature_group_engine.py
python/tests/core/test_great_expectation_engine.py
python/tests/core/test_validation_report_engine.py
python/tests/fixtures/expectation_suite_fixtures.json
python/tests/fixtures/ge_expectation_fixtures.json
python/tests/test_expectation_suite.py
python/tests/test_ge_expectation.py

JIRA Issue: -
Related PRs: -
```
```

[HOPSWORKS-3230][FSTORE-330] Single expectation api

---

.github/workflows/mkdocs-master.yml

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-167] Remove dev/SNAPSHOT version from hsfs, hsml and hopsworks API docs

---

java/src/main/java/com/logicalclocks/hsfs/engine/FeatureViewEngine.java
python/hsfs/core/feature_view_api.py
python/hsfs/core/feature_view_engine.py
python/hsfs/feature_view.py

- Implement `fv.update` for python client
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-322] Update fv description

---

java/src/main/java/com/logicalclocks/hsfs/Feature.java
java/src/main/java/com/logicalclocks/hsfs/TrainingDatasetFeature.java
java/src/main/java/com/logicalclocks/hsfs/engine/FeatureViewEngine.java
java/src/test/java/com/logicalclocks/hsfs/engine/FeatureViewEngineTest.java
python/hsfs/constructor/join.py
python/hsfs/constructor/query.py
python/hsfs/core/feature_view_engine.py
python/hsfs/feature.py
python/hsfs/training_dataset_feature.py
python/tests/core/test_feature_view_engine.py

- Enable attaching label by feature group
- Add unit tests
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-381] Enable attaching label by feature group

---

python/hsfs/core/feature_group_engine.py
python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-395] Fix great_expectation_engine call in fg.save

---

java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupBase.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-397] Add type to feature group dto

---

python/hsfs/expectation_suite.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-387] Remove parsing ids from href for expectation suite

---

python/hsfs/__init__.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-199] Should be possible to get python library version using .__version__

---

python/hsfs/core/feature_view_engine.py
python/tests/core/test_feature_view_engine.py

1. Check if prefix is empty.
2. Add a test cases.
3. Rename shadowed variables.
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-410][FSTORE-381][APPEND] Enable attaching label by feature group

---

python/hsfs/core/job_configuration.py
python/tests/core/test_job_configuration.py

copy paste bug.
JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-420
Related PRs: -
```
```

[FSTORE-420] Feature Group insertion job from Python does not apply spark resources correctly

---

python/hsfs/feature_group.py
python/tests/test_feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-433] Add support for event_time as single item list for compatibility purpose

---

python/hsfs/feature_view.py
python/tests/test_feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-385] Handle same instance of transformation function for multiple features properly

---

python/hsfs/core/validation_report_engine.py
python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-444] data validation minor bug fixes for python client

---

java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
java/src/main/java/com/logicalclocks/hsfs/StreamFeatureGroup.java
java/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupUtils.java
java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupBase.java
python/hsfs/core/feature_group_engine.py
python/hsfs/core/kafka_api.py
python/hsfs/engine/python.py
python/hsfs/engine/spark.py
python/hsfs/feature_group.py
python/tests/core/test_feature_group_engine.py
python/tests/engine/test_python.py
python/tests/engine/test_spark.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-388] Weird values in Online FS, after using .append_feature

---

python/hsfs/util.py
python/tests/test_util.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-453] Restore old version of date converter

---

python/hsfs/engine/spark.py

This PR adds full traceback to spark engine exception
JIRA Issue: FSTORE-425
Related PRs: -
```
```

[FSTORE-452] Add traceback to spark engine save exception

---

python/hsfs/feature_view.py

- Add doc string to feature view
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-430] Add doc string to feature view

---

java/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupBaseEngine.java
java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupBase.java
java/src/test/java/com/logicalclocks/hsfs/metadata/TestFeatureGroup.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-476] Schema not updated for hsfs java client after append

---

python/hsfs/core/job_configuration.py
python/tests/core/test_job_configuration.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-489] Bump spark driver memory to 2GB and executor memory to 4GB

---

python/hsfs/connection.py
python/hsfs/expectation_suite.py
python/hsfs/feature.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py

added code snippets for API,
FeatureStore
Feature Group
Feature
Connection
ExpectationSuite
topics

Feature Store API, added snippets

---

.gitignore
java/pom.xml
java/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupUtils.java
java/src/main/java/com/logicalclocks/hsfs/engine/hudi/HudiEngine.java
python/hsfs/core/hudi_engine.py
python/hsfs/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-333] Hudi should use HMS hive sync instead of jdbc

---

java/src/main/java/com/logicalclocks/hsfs/ExternalFeatureGroup.java
java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupBase.java
python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-425] throw meaningful error if user tries to set time_travel_format=None in a Python kernel

---

python/hsfs/constructor/query.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py
python/hsfs/feature_view.py
python/hsfs/transformation_function.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-499][append] - Fix Python style

---

java/src/main/java/com/logicalclocks/hsfs/metadata/CodeApi.java
java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupApi.java
java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureViewApi.java
java/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksClient.java
java/src/main/java/com/logicalclocks/hsfs/metadata/QueryConstructorApi.java
java/src/main/java/com/logicalclocks/hsfs/metadata/StatisticsApi.java
java/src/main/java/com/logicalclocks/hsfs/metadata/TagsApi.java
java/src/main/java/com/logicalclocks/hsfs/metadata/TrainingDatasetApi.java
java/src/test/java/com/logicalclocks/hsfs/metadata/TestHopsworksClient.java

JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-436
Related PRs: -
```
```

[FSTORE-436] HSFS Java doesn't serialize JSONs correctly

---

python/hsfs/client/base.py
python/hsfs/client/external.py
python/hsfs/expectation_suite.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py
python/hsfs/feature_view.py
python/hsfs/training_dataset.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-407] API Doc should include full package name for the RestAPIError

---

java/src/main/java/com/logicalclocks/hsfs/Feature.java
java/src/main/java/com/logicalclocks/hsfs/constructor/SqlFilterCondition.java
java/src/test/java/com/logicalclocks/hsfs/TestFeature.java
python/hsfs/constructor/filter.py
python/hsfs/constructor/query.py
python/hsfs/feature.py
python/tests/test_feature.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-309] Add support for like operator in query filter

---

java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupBase.java
java/src/test/java/com/logicalclocks/hsfs/TestFeatureGroupBase.java
java/src/test/java/com/logicalclocks/hsfs/engine/TestFeatureViewEngine.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-508] NPE when creating feature view with labels

---

python/hsfs/core/job.py
python/hsfs/core/job_api.py
python/hsfs/engine/python.py
python/tests/engine/test_python.py
python/tests/engine/test_python_writer.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-467] Make it easier to start the backfill job from python

---

python/hsfs/core/great_expectation_engine.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-454] Add print to warn user of validation result

---

python/hsfs/core/expectation_suite_engine.py
python/hsfs/expectation_suite.py
python/hsfs/ge_expectation.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-509] Metadata update on setter for expectation suite

---

python/hsfs/core/feature_group_engine.py
python/hsfs/core/great_expectation_engine.py
python/hsfs/core/validation_result_engine.py
python/hsfs/feature_group.py
python/hsfs/ge_validation_result.py
python/hsfs/validation_report.py
python/tests/core/test_validation_result_engine.py
python/tests/fixtures/validation_report_fixtures.json
python/tests/test_validation_report.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-510] ingestion result changes

---

java/src/main/java/com/logicalclocks/hsfs/FeatureView.java
java/src/main/java/com/logicalclocks/hsfs/TrainingDataset.java
java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupBase.java
python/hsfs/engine/python.py
python/hsfs/feature_group.py
python/hsfs/feature_view.py
python/hsfs/training_dataset.py
python/hsfs/util.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-373] Remove job when a fg or fv is deleted.

---

java/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupBase.java
python/hsfs/feature_group.py
python/tests/test_feature_group.py

Add `include_primary_key=True, include_event_time=True` to `select_all`
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-422] Expand select_all

---

python/hsfs/core/explicit_provenance.py

JIRA Issue: -
https://hopsworks.atlassian.net/browse/FSTORE-520
Related PRs: -
```
```

[FSTORE-520] new exception cause field

---

python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-530] Add overwrite flag and logic in fg.save_validation_suite

---

python/hsfs/core/transformation_function_engine.py
python/hsfs/engine/python.py
python/hsfs/transformation_function.py
python/hsfs/util.py
python/tests/core/test_transformation_function_engine.py
python/tests/test_transformation_function.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-339] Handle legacy spark type

---

python/hsfs/core/explicit_provenance.py

JIRA Issue: https://hopsworks.atlassian.net/browse/FSTORE-520 
Related PRs: -
```
```

[FSTORE-520][APPEND] Feature view - explicit provenance if parent feature group is deleted

---

python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-552] Convert dataframe to native in validate

---

java/pom.xml
python/hsfs/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Bump development version to 3.2.0-SNAPSHOT/3.2.0.dev1

---

python/.pre-commit-config.yaml

JIRA Issue: -
Related PRs: -
```
```

Fix pre-commit with flake8 github repo

---

auto_doc.py
docs/templates/api/links.md
mkdocs.yml
python/hsfs/core/explicit_provenance.py
python/hsfs/expectation_suite.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py
python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-555] Explicit provenance API documentation

---

auto_doc.py
docs/templates/api/links.md
mkdocs.yml
python/hsfs/core/explicit_provenance.py
python/hsfs/expectation_suite.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py
python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-555] Explicit provenance API documentation (#910)

---

python/hsfs/feature_group.py
python/hsfs/feature_view.py

- Add examples about include_primary_key and include_event_time
- Add doc string for extra_filter
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-556] Add examples about include_primary_key and include_event_time

---

python/hsfs/core/feature_view_engine.py
python/tests/core/test_feature_view_engine.py

- Attach transformation functions to fv and td features on save and get
- Add unit tests
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-516] Attach tf to features

---

java/src/test/java/com/logicalclocks/hsfs/engine/TestFeatureViewEngine.java
python/tests/core/test_feature_view_engine.py
python/tests/core/test_transformation_function_engine.py

- Add unit tests for testing attaching transformation function and label in self join query
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-558] Test self join query for tf and label

---

python/hsfs/engine/python.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-434] Improve Kafka message delivery callback error handling

---

python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-589] Document behaviour of get_feature_vector(s) for missing PK values

---

python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-589] Document behaviour of get_feature_vector(s) for missing PK values (#915)

---

python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-581] Update fv doc string

---

.github/workflows/python-lint.yml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-621] Make unit tests run on hsfs branch-3.1

---

python/hsfs/feature_view.py

(cherry picked from commit 109c16af5b551d0380df7fc98905e05641357656)
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-581] Update fv doc string (#917)

---

python/hsfs/core/vector_server.py
python/hsfs/engine/python.py
python/tests/engine/test_python.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-639] Pin SQLalchemy version or upgrade to new 2.0.0 version

---

python/hsfs/constructor/query.py
python/hsfs/engine/python.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py
python/hsfs/feature_view.py

- Add doc string for hive config
- Pass hive config to pyhive connector
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-483] Handle hive config

---

python/hsfs/engine/python.py
python/hsfs/engine/spark.py

JIRA Issue: -
Related PRs: -
```
```

[3.1][FSTORE-689] Shallow dataframe copy hides TZ bug

---

java/pom.xml
python/hsfs/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release hsfs version 3.1.0rc2

---

python/hsfs/feature_group.py
python/hsfs/feature_store.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-658] Incomplete doc string of create_external_feature_group

---

python/hsfs/core/vector_server.py
python/hsfs/feature_view.py
python/hsfs/util.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-694] Make SqlAlchemy configurable

---

java/src/main/java/com/logicalclocks/hsfs/ExternalFeatureGroup.java
java/src/main/java/com/logicalclocks/hsfs/FeatureGroup.java
java/src/main/java/com/logicalclocks/hsfs/StreamFeatureGroup.java
java/src/main/java/com/logicalclocks/hsfs/engine/ExternalFeatureGroupEngine.java
java/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupEngine.java
java/src/main/java/com/logicalclocks/hsfs/engine/SparkEngine.java
java/src/main/java/com/logicalclocks/hsfs/engine/VectorServer.java
java/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksExternalClient.java
java/src/test/java/com/logicalclocks/hsfs/metadata/TestTagsApi.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-607] Investigate hsfs java resource leaks

---

utils/python/hsfs_utils.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-712] Add dummy feature monitoring job to hsfs_util

---

python/hsfs/engine/python.py

…c type (#944)
when computing pandas statistics check if mean is numeric type
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-726] when computing pandas statistics check if mean is numeric

---

java/pom.xml
python/hsfs/core/external_feature_group_engine.py
python/hsfs/feature_group.py
python/hsfs/version.py
python/tests/core/test_external_feature_group_engine.py
utils/java/pom.xml
utils/python/hsfs_utils.py

JIRA Issue: -
Related PRs: -
```
```

Release version 3.1.1-RC0

---

.github/workflows/mkdocs-master.yml
.github/workflows/mkdocs-release.yml
.gitignore
docs/js/inject-api-links.js
docs/overrides/partials/tabs-item.html

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-619] Add github actions to publish javadoc

---

python/setup.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-759] Relax fastavro requirements in hsfs

---

java/pom.xml
python/hsfs/version.py
python/setup.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 3.1.1rc1

---

python/setup.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-758] Limit pandas version

---

python/hsfs/core/feature_monitoring_config_engine.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-721] fix trigger monitoring job

---

python/setup.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-774] Remove gcsfs dependency

---

python/hsfs/engine/python.py
python/tests/engine/test_python.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-776] Fix split ratio comparison

---

python/setup.py

JIRA Issue: -
Related PRs: -
```
```

[CLOUD-390] Avro 1.11.0

---

java/src/main/java/com/logicalclocks/hsfs/engine/hudi/DeltaStreamerKafkaSource.java
java/src/main/java/com/logicalclocks/hsfs/engine/hudi/HudiEngine.java
python/hsfs/engine/spark.py
utils/java/src/main/java/com/logicalclocks/utils/MainClass.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-782] Allow resetting kafka offsets for stream feature groups after backup/restore

---

utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-789] append - fix hsfs util java

---

python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-743][append] Allow reading from online in python engine from external feature groups

---

java/spark/src/main/java/com/logicalclocks/hsfs/spark/ExternalFeatureGroup.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/FeatureGroupEngine.java
java/spark/src/test/java/com/logicalclocks/hsfs/spark/TestExternalFeatureGroup.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-743][append][java] Add support for insert to external feature groups online

---

java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Bump development version to 3.3.0-SNAPSHOT/3.3.0.dev1

---

python/hsfs/core/job.py
python/hsfs/core/job_api.py
python/hsfs/engine/python.py
python/tests/engine/test_python.py
python/tests/engine/test_python_writer.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-815] Auto-reset Feature Group Kafka offset after topic recreation/upgrade/restore

---

java/pom.xml
python/hsfs/version.py
python/setup.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Limit Pandas version in 3.0.x release series

---

python/hsfs/core/arrow_flight_client.py
python/hsfs/core/variable_api.py

This PR adds support for external clients via loadbalancer and external clients on dev vms (localhost) as fallback
JIRA Issue: FSTORE-822
Related PRs: -
```
```

[FSTORE-822] External client access Flyingduck

---

.github/workflows/python-lint.yml
python/setup.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-841] Relax confluent-kafka dependency to support python 3.10

---

.github/workflows/mkdocs-release.yml

JIRA Issue: -
Related PRs: -
```
```

Remove latest tag from 3.1 docs

---

python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[3.2] Fix multi-part insert docstring

---

python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

Fix multi-part insert docstring

---

python/hsfs/feature_group_commit.py
python/tests/fixtures/feature_group_commit_fixtures.json
python/tests/test_feature_group_commit.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-846] Feature Group commit_details fails in certain cases

---

python/hsfs/engine/python.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-851] Increase Kafka List Topics Timeout in HSFS

---

java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/SparkEngine.java
python/hsfs/engine/spark.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-861] fetch external broker address for spark/pyspark

---

java/flink/src/main/java/com/logicalclocks/hsfs/flink/StreamFeatureGroup.java
java/flink/src/main/java/com/logicalclocks/hsfs/flink/engine/FeatureGroupEngine.java
java/flink/src/main/java/com/logicalclocks/hsfs/flink/engine/FlinkEngine.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-751][APPEND] add external kafka listeners for flink engine

---

java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-864] Downgrade avro version in hsfs to 1.8.2

---

utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-861][APPEND] bump util version

---

java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/FeatureDescriptiveStatistics.java
python/hsfs/core/builtin_transformation_function.py
python/hsfs/core/feature_descriptive_statistics.py
python/hsfs/core/feature_view_engine.py
python/hsfs/core/statistics_engine.py
python/hsfs/core/transformation_function_engine.py
python/hsfs/core/vector_server.py
python/hsfs/engine/python.py
python/hsfs/feature_group.py
python/hsfs/training_dataset.py
python/tests/core/test_statistics_engine.py
python/tests/core/test_transformation_function_engine.py
python/tests/engine/test_python.py
python/tests/engine/test_python_spark_transformation_functions.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-808] (Append) Fixes for training dataset statistics

---

python/hsfs/core/statistics_engine.py
python/hsfs/feature_group.py
python/hsfs/training_dataset.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-859] Fixes for statistics tests

---

python/hsfs/engine/python.py
python/hsfs/engine/spark.py
python/hsfs/storage_connector.py
python/tests/test_storage_connector.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-647][FSTORE-646][FSTORE-644] Bigquery and GCS python validation and path fix

---

python/hsfs/core/statistics_engine.py
python/hsfs/feature_group.py
python/hsfs/training_dataset.py

JIRA Issue: -
Related PRs: -
```
```

Fix error code

---

auto_doc.py
python/hsfs/core/explicit_provenance.py
python/hsfs/core/feature_group_base_engine.py
python/hsfs/core/feature_monitoring_config.py
python/hsfs/core/feature_monitoring_config_engine.py
python/hsfs/core/feature_monitoring_result.py
python/hsfs/core/feature_monitoring_result_engine.py
python/hsfs/core/feature_view_engine.py
python/hsfs/core/monitoring_window_config_engine.py
python/hsfs/core/statistics_engine.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py
python/hsfs/feature_view.py
python/hsfs/util.py
python/tests/core/test_monitoring_window_config_engine.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-867] Fixing end to end tests for FG, FV not working

---

python/hsfs/constructor/external_feature_group_alias.py
python/hsfs/constructor/fs_query.py
python/hsfs/constructor/query.py
python/hsfs/core/feature_group_api.py
python/hsfs/core/feature_view_engine.py
python/hsfs/core/spine_group_engine.py
python/hsfs/engine/python.py
python/hsfs/engine/spark.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py
python/hsfs/feature_view.py
python/tests/core/test_feature_view_engine.py
python/tests/fixtures/external_feature_group_alias_fixtures.json
python/tests/fixtures/fs_query_fixtures.json
python/tests/fixtures/query_fixtures.json

- add spine group creation
- add spine engine
- fix
- move features property to base class
- small fix
- cache df
- fix
- get or create and alias fix
- fix
- use spine fs
- pass dataframe down
- print
- dirty type check to avoid circluar dimport
- fix dirty hack
- fix
- pass down spine
- train_test_split with spine
- pass down spine
- change get or create error code
- allow passing spine group
- raise useful exception
- add docs
- fix unit tests
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-849] Support Spine Dataframes for batch data and training datasets

---

python/hsfs/core/feature_monitoring_config.py
python/hsfs/core/monitoring_window_config_engine.py
python/hsfs/core/statistics_engine.py
python/hsfs/feature_group.py
python/hsfs/statistics.py
python/tests/core/test_monitoring_window_config_engine.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-871] Add rounding to the latest hour if event time window

---

java/hsfs/src/main/java/com/logicalclocks/hsfs/FeatureGroupCommit.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/hudi/HudiEngine.java
python/hsfs/core/hudi_engine.py
python/hsfs/feature_group_commit.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-737] Show archived commits in Feature Group activity page

---

auto_doc.py
docs/templates/api/spine_group_api.md
mkdocs.yml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-849][append] Add spine group api docs

---

python/hsfs/core/feature_monitoring_config.py
python/hsfs/core/feature_monitoring_config_engine.py
python/hsfs/core/monitoring_window_config_engine.py
python/hsfs/core/statistics_api.py
python/hsfs/core/statistics_engine.py
python/hsfs/feature_group.py
python/hsfs/feature_view.py
python/hsfs/statistics.py
python/tests/core/test_monitoring_window_config_engine.py
python/tests/core/test_statistics_engine.py
python/tests/fixtures/feature_monitoring_config_fixtures.json
python/tests/fixtures/statistics_fixtures.json
python/tests/test_statistics.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-868] Support feature view statistics with event and commit times

---

java/pom.xml
python/.pre-commit-config.yaml
python/hsfs/engine/python.py
python/hsfs/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 3.1.1rc6

---

python/hsfs/constructor/filter.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-870] Issues including None/Nan/Null values in queries on feature views

---

java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/Statistics.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/StatisticsEngine.java
python/hsfs/core/statistics_api.py
python/hsfs/core/statistics_engine.py
python/hsfs/statistics.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-886] Support fv statistics on transformed data

---

java/pom.xml
python/hsfs/constructor/filter.py
python/hsfs/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release version 3.1.2-RC0

---

java/hsfs/src/main/java/com/logicalclocks/hsfs/StorageConnector.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/util/Constants.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/SparkEngine.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/util/StorageConnectorUtils.java
java/spark/src/test/java/com/logicalclocks/hsfs/spark/TestStorageConnector.java
python/hsfs/engine/spark.py
python/hsfs/storage_connector.py
python/tests/engine/test_spark.py
python/tests/fixtures/storage_connector_fixtures.json
python/tests/test_storage_connector.py

Adds spark options support for S3 connector
JIRA Issue: -
https://hopsworks.atlassian.net/browse/FSTORE-577
Related PRs: -
```
```

[FSTORE-577] add spark options for s3

---

python/setup.py

JIRA Issue: -
https://hopsworks.atlassian.net/browse/FSTORE-894
Related PRs: -
```
```

[FSTORE-894] Add missing mkdocs-minify-plugin for building docs

---

python/setup.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-586] Upgrade great expectations to 0.14.13

---

python/hsfs/engine/python.py

This PR adds workaround for missing pd.NA support in fastavro. Fixes ingestion for nullable pandas type like Int64
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-911] Added pd.NA support

---

python/setup.py
python/tests/engine/test_spark.py
python/tests/fixtures/expectation_suite_fixtures.json
python/tests/fixtures/feature_group_fixtures.json
python/tests/test_expectation_suite.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-586] Upgrade great expectations to 0.14.13 (#1041)

---

java/pom.xml
python/hsfs/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 3.0.8

---

java/pom.xml
python/hsfs/constructor/join.py
python/hsfs/version.py
python/tests/constructor/test_join.py
python/tests/fixtures/feature_view_fixtures.json
python/tests/fixtures/join_fixtures.json
python/tests/fixtures/query_fixtures.json
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release version 3.1.2rc1

---

java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/constructor/join.py
python/hsfs/version.py
python/tests/constructor/test_join.py
python/tests/fixtures/feature_view_fixtures.json
python/tests/fixtures/join_fixtures.json
python/tests/fixtures/query_fixtures.json
python/tests/test_feature_group_writer.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release version 3.2.0rc5

---

python/hsfs/engine/python.py
python/tests/engine/test_python.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-912] Fixed arrow schema for complex features

---

python/hsfs/core/expectation_suite_engine.py
python/hsfs/expectation_suite.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-917] Decamelize to update metadata + minor cleanup

---

java/hsfs/src/main/java/com/logicalclocks/hsfs/engine/VectorServer.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/Variable.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/VariablesApi.java
python/hsfs/constructor/join.py
python/hsfs/constructor/query.py
python/hsfs/core/arrow_flight_client.py
python/hsfs/core/code_engine.py
python/hsfs/core/expectation_suite_engine.py
python/hsfs/core/feature_group_engine.py
python/hsfs/core/great_expectation_engine.py
python/hsfs/core/hudi_engine.py
python/hsfs/core/job_configuration.py
python/hsfs/core/variable_api.py
python/hsfs/core/vector_server.py
python/hsfs/engine/python.py
python/hsfs/engine/spark.py
python/hsfs/feature_group_writer.py
python/hsfs/split_statistics.py
python/hsfs/training_dataset_split.py
python/hsfs/util.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-924] HSFS External client doens't handle HA services

---

python/setup.py

… schema parsing
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-917][append] Add lower bound to pyarrow

---

python/hsfs/core/expectation_suite_engine.py
python/hsfs/expectation_suite.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-917] Backport updating expectation suite metadata with setter

---

java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release version 3.2.0

---

python/hsfs/core/expectation_suite_engine.py
python/hsfs/expectation_suite.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-917] Backport metadata update for expectation suite

---

python/hsfs/core/feature_monitoring_config.py
python/hsfs/core/feature_monitoring_config_engine.py
python/hsfs/core/job_scheduler.py
python/hsfs/core/job_scheduler_api.py
python/hsfs/core/job_scheduler_engine.py
python/hsfs/feature_group.py
python/hsfs/feature_view.py
python/tests/core/test_job_scheduler.py
python/tests/fixtures/job_scheduler_fixtures.json

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-908] Upgrade the job scheduler to use cron expression

---

python/hsfs/core/feature_group_engine.py
python/hsfs/feature_group.py
python/tests/core/test_feature_group_engine.py
python/tests/test_feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-931] Add support for creating feature group metadata through save method

---

python/hsfs/core/vector_server.py
python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-935] add return type to get_feature_vector(s)

---

java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

[dev_branch_3.4.0] Bump development version to 3.4.0-SNAPSHOT/3.4.0.dev1

---

java/pom.xml
python/hsfs/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 3.1

---

python/hsfs/core/job.py
python/hsfs/engine/python.py
python/hsfs/feature_group.py
python/hsfs/feature_group_writer.py
python/tests/engine/test_python.py
python/tests/engine/test_python_writer.py
python/tests/test_feature_group.py
python/tests/test_feature_group_writer.py
utils/java/src/main/java/com/logicalclocks/utils/MainClass.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-939] Change name of Stream Feature Group's DeltaStreamer Job

---

python/hsfs/constructor/query.py
python/hsfs/feature_group.py
python/hsfs/feature_view.py

This PR updates docstring for arrow flight server
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-844] Added arrow flight server read_options

---

python/hsfs/constructor/query.py
python/hsfs/feature_group.py
python/hsfs/feature_view.py

(cherry picked from commit a00634db6cb079b98f7da32f121d8fc2d41aaad6)
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-884] Added arrow flight server read_options (#1075)

---

python/hsfs/core/feature_group_api.py
python/hsfs/core/vector_server.py
python/hsfs/feature_store.py
python/hsfs/feature_view.py
python/hsfs/serving_key.py

- add `allow_missing` to `get_feature_vector(s)` and return feature vector with missing value 
- fix the logic of required primary key (serving key)
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-921] Resolve serving key in feature view

---

python/hsfs/core/arrow_flight_client.py
python/hsfs/engine/python.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-884] Renaming ArrowFlight Server

---

java/spark/src/main/java/com/logicalclocks/hsfs/spark/util/StorageConnectorUtils.java
java/spark/src/test/java/com/logicalclocks/hsfs/spark/TestStorageConnector.java
python/hsfs/engine/python.py
python/hsfs/storage_connector.py
python/tests/test_storage_connector.py

JIRA Issue: -
https://hopsworks.atlassian.net/browse/FSTORE-647
https://hopsworks.atlassian.net/browse/FSTORE-942
Related PRs: -
```
```

[FSTORE-942][FSTORE-647] adls path validation and default path fixes for path connectors

---

python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-907] Fix recompute statistics for non-time travel fgs

---

python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[APPEND][FSTORE-955] Fix get batch data

---

python/hsfs/core/feature_view_engine.py
utils/python/hsfs_utils.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-906] Fix compute_stats job for TDs

---

java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/SparkEngine.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/util/StorageConnectorUtils.java
python/hsfs/engine/python.py
python/hsfs/engine/spark.py
python/tests/engine/test_python.py
python/tests/engine/test_spark.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-654] Should throw proper error if data format is not provided.

---

java/spark/src/main/java/com/logicalclocks/hsfs/spark/StreamFeatureGroup.java
python/hsfs/engine/python.py
python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-842] Setting fg.insert(storage="online") adds data to offline as well

---

python/hsfs/core/arrow_flight_client.py
python/hsfs/storage_connector.py

This PR adds BigQuery support to DuckDB with ArrowFlight Server
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-984] Added bigquery arrow flight storage connector

---

java/beam/src/main/java/com/logicalclocks/hsfs/beam/engine/BeamEngine.java
java/flink/src/main/java/com/logicalclocks/hsfs/flink/engine/FlinkEngine.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/engine/EngineBase.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/SparkEngine.java
java/spark/src/test/java/com/logicalclocks/hsfs/spark/engine/TestSparkEngine.java
python/hsfs/engine/python.py
python/hsfs/engine/spark.py
python/tests/engine/test_python.py
python/tests/engine/test_spark.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-840][APPEND] Use existing Kafka cluster

---

java/hsfs/src/main/java/com/logicalclocks/hsfs/engine/FeatureGroupEngineBase.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupApi.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/QueryConstructorApi.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-993] HSFS Java should use UTF-8 when creating the StringEntity

---

java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/version.py
python/setup.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-997] Pin pandas<2.1.0 for hsfs

---

.github/workflows/java-ut.yml
java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/SparkEngine.java
java/spark/src/test/java/com/logicalclocks/hsfs/spark/TestStorageConnector.java

JIRA Issue: -
Related PRs: -
```
```

Add maven clean in java ut

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/version.py

JIRA Issue: -
Related PRs: -
```
```

Prepare for 3.5.0 development

---

utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Bump HSFS utils version

---

python/setup.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-745] Support python 3.11 for the client APIs

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/version.py
utils/java/pom.xml

**DO NOT MERGE UNTIL APP UPGRADE IS COMPLETE**
JIRA Issue: -
Related PRs: -
```
```

[CLOUD-658] Release version 3.4.2

---

python/hsfs/core/arrow_flight_client.py
python/hsfs/engine/__init__.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1050] Reset arrow_flight_client on close

---

python/hsfs/core/arrow_flight_client.py

JIRA Issue: - https://hopsworks.atlassian.net/browse/FSTORE-1071
Related PRs: -
```
```

[FSTORE-1071] Replace all feature store names for ArrowFlight

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/version.py
python/setup.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release version 3.4.4

---

python/hsfs/core/feature_group_base_engine.py
python/hsfs/core/kafka_api.py
python/tests/core/test_feature_group_engine.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1075] Cannot get schema from shared project

---

java/pom.xml
java/spark/pom.xml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1085] Add profiles to HSFS to support multiple Spark version

---

java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/SparkEngine.java
java/spark/src/test/java/com/logicalclocks/hsfs/spark/engine/TestSparkEngine.java
python/hsfs/engine/spark.py
python/tests/engine/test_spark.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1084] Change spark query name

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/core/code_engine.py
python/hsfs/version.py
python/tests/core/test_code_engine.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1089] Remove databricks code copy and release 3.5.0rc1

---

.github/workflows/python-lint.yml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1097] Disable usage for unit test

---

.github/workflows/python-lint.yml
python/setup.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-802] Python 3.12 support for clients

---

python/setup.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1104] Pin numpy < 2

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/version.py
python/setup.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 3.5.0rc2

---

python/hsfs/client/external.py
python/hsfs/connection.py
python/hsfs/core/feature_view_engine.py
python/hsfs/engine/__init__.py
python/hsfs/engine/spark_no_metastore.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1115] Introduce new spark-no-metastore engine

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/client/external.py
python/hsfs/connection.py
python/hsfs/core/feature_view_engine.py
python/hsfs/engine/__init__.py
python/hsfs/engine/spark_no_metastore.py
python/hsfs/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release 3.5.0-RC3

---

java/hsfs/src/main/java/com/logicalclocks/hsfs/StorageConnector.java
python/hsfs/storage_connector.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1021] Add a warning when using externally managed Kafka

---

python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1052] Update the docs to include Kafka config variables for throughput

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/core/feature_group_base_engine.py
python/hsfs/core/kafka_api.py
python/hsfs/version.py
python/tests/core/test_feature_group_engine.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Revert [FSTORE-1075] and release 3.5.0-RC4

---

python/hsfs/core/opensearch.py
python/hsfs/core/opensearch_api.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1128] Fallback to head node host in opensearch api

---

java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/hudi/DeltaStreamerAvroDeserializer.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/hudi/DeltaStreamerKafkaSource.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1131] DeltaStreamer job fails when feature group has complex feature

---

java/beam/src/main/java/com/logicalclocks/hsfs/beam/HopsworksConnection.java
java/beam/src/main/java/com/logicalclocks/hsfs/beam/engine/BeamEngine.java
java/flink/src/main/java/com/logicalclocks/hsfs/flink/HopsworksConnection.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/CodeApi.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/DatasetApi.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupApi.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/FeatureStoreApi.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/FeatureViewApi.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksClient.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/KafkaApi.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/QueryConstructorApi.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/StatisticsApi.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/StorageConnectorApi.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/TagsApi.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/TrainingDatasetApi.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/HopsworksConnection.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/SparkEngine.java
java/spark/src/test/java/com/logicalclocks/hsfs/spark/TestFeatureGroup.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1138] Java client is not designed to work with shared feature store

---

java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/FeatureGroupApi.java
java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/KafkaApi.java
java/spark/src/test/java/com/logicalclocks/hsfs/spark/TestFeatureGroup.java
python/hsfs/core/feature_group_base_engine.py
python/hsfs/core/kafka_api.py
python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1130] Get schema from shared project

---

python/hsfs/engine/python.py
python/setup.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1055] Support pandas 2.1.*

---

python/setup.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1142] Remove markupsafe<2.1.0 pinning

---

python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1034] .select() method should not default to empty list

---

python/hsfs/core/vector_server.py

- Fix wrong serving_keys causing failure in loadtest `test_similarity_search.py` 
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1116][APPEND] fix serving_keys for similarity search

---

python/hsfs/core/feature_view_api.py
python/hsfs/core/feature_view_engine.py
python/hsfs/feature_view.py
python/hsfs/training_dataset.py
python/tests/core/test_arrow_flight_client.py
python/tests/core/test_feature_view_engine.py
utils/python/hsfs_utils.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1152] Add support for listing td metadata objects from a feature view

---

python/setup.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-944] Pin upper pandas to 2.1.4

---

python/hsfs/engine/python.py
python/tests/engine/test_python.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-934] Use more precise statistics

---

python/hsfs/constructor/filter.py
python/hsfs/core/vector_db_client.py
python/hsfs/feature_group.py
python/tests/core/test_vector_db_client.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1132] Enable filtering in find_neighbors

---

.github/workflows/python-lint.yml
java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/engine/python.py
python/hsfs/version.py
python/setup.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release version 3.4.7

---

python/setup.py
python/tests/engine/test_python_reader.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1193] HSFS python tests fail after moto has been updated

---

python/hsfs/core/vector_db_client.py
python/tests/core/test_vector_db_client.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1164] Support composite primary key in similarity search

---

python/hsfs/constructor/query.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1203] 'FeatureGroup' object has no attribute 'time_travel_format'

---

python/hsfs/engine/spark.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1180][UNDO] metastore confuses partitions when reading fg and returns wrong data

---

python/hsfs/embedding.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1190] Attach model to embedding feature

---

python/hsfs/engine/python.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1187] Execution failing with framework_failure causes insert to hang forever

---

java/hsfs/src/main/java/com/logicalclocks/hsfs/FeatureGroupBase.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1234] deep copy feature object for updateFeatureDescription in Java client

---

auto_doc.py
docs/templates/api/feature_descriptive_statistics_api.md
docs/templates/api/feature_monitoring_config_api.md
docs/templates/api/feature_monitoring_result_api.md
docs/templates/api/feature_monitoring_window_config_api.md
docs/templates/api/split_statistics_api.md
docs/templates/api/statistics_api.md
docs/templates/api/validation_report_api.md
mkdocs.yml
python/hsfs/core/feature_descriptive_statistics.py
python/hsfs/core/feature_monitoring_config.py
python/hsfs/core/feature_monitoring_result.py
python/hsfs/core/monitoring_window_config.py
python/hsfs/feature_store.py
python/hsfs/split_statistics.py
python/hsfs/statistics.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-612] Improve API reference for feature monitoring

---

python/hsfs/core/feature_view_engine.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1181][APPEND] Check helper column name clash if required

---

python/hsfs/core/vector_db_client.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1276] Use a larger value of k in find_neighbors when using project index

---

python/hsfs/core/vector_server.py

JIRA Issue: -
https://hopsworks.atlassian.net/browse/FSTORE-1271
Related PRs: -
```
```

[FSTORE-1271][FSTORE-1116] fix for no primary key supplied for label FG

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/core/vector_server.py
python/hsfs/version.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1271][FSTORE-1116] fix no label FG primary key supplied (#1237)

---

python/hsfs/core/monitoring_window_config_engine.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1287] Use before_transformation statistics when appropriate

---

java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/hudi/DeltaStreamerAvroDeserializer.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/hudi/HudiEngine.java
python/hsfs/core/vector_server.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1278] Recreated FG could be blacklisted in onlinefs if schema ID matches

---

.gitignore
python/hsfs/client/auth.py
python/hsfs/client/exceptions.py
python/hsfs/client/external.py
python/hsfs/client/hopsworks.py
python/hsfs/client/online_store_rest_client.py
python/hsfs/core/online_store_rest_client_api.py
python/hsfs/core/online_store_rest_client_engine.py
python/hsfs/core/vector_server.py
python/hsfs/feature_store.py
python/hsfs/feature_view.py
python/hsfs/util.py
python/setup.py
python/tests/core/test_online_store_rest_client.py
python/tests/core/test_online_store_rest_client_api.py
python/tests/core/test_online_store_rest_client_enigne.py
python/tests/core/test_vector_server.py
python/tests/fixtures/backend_fixtures.py
python/tests/fixtures/feature_view_fixtures.json
python/tests/fixtures/rondb_server_fixtures.json
python/tests/fixtures/serving_keys_fixtures.json
python/tests/fixtures/training_dataset_feature_fixtures.json

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1185] Online Store REST Client for 3.7

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/version.py
python/setup.py
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

Release version 3.7.0-RC8

---

docs/templates/api/links.md
python/hsfs/core/explicit_provenance.py
python/hsfs/core/feature_group_api.py
python/hsfs/core/feature_group_base_engine.py
python/hsfs/core/feature_view_api.py
python/hsfs/core/feature_view_engine.py
python/hsfs/feature_view.py
python/hsfs/training_dataset.py

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-936] Explicit model provenance

---

python/hsfs/client/exceptions.py
python/hsfs/core/opensearch.py
python/hsfs/core/vector_db_client.py
python/tests/core/test_opensearch.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1305] Handle requested result is too large in vector database

---

.github/workflows/python-lint.yml
python/hsfs/core/explicit_provenance.py
python/hsfs/feature_view.py
python/hsfs/training_dataset.py

Fixed in the splits setter and reverted to the original empty dict passing
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1306][Append] Handle None in Training Dataset splits setter

---

python/hsfs/core/delta_engine.py
python/hsfs/core/feature_group_engine.py
python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1237] implement commit_delete_records method for DELTA enabled feature groups

---

auto_doc.py

This will need to be cherrypicked to other branches, excuse the minor reformatting
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1339] Fix source links in docs to direct to correct release branch

---

auto_doc.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1339] Fix source links generation to point to repo at correct commit

---

python/setup.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1284] install aiomysql from LC fork

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/version.py
utils/java/pom.xml

JIRA Issue: - 
https://hopsworks.atlassian.net/browse/CLOUD-718
Related PRs: -
```
```

[CLOUD-718] Release 3.7.1

---

python/hsfs/engine/spark.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1354] Fix spark engine udf time series split test on windows duplicating code instead of importing

---

README.md
docs/js/inject-api-links.js
docs/js/version-select.js
docs/overrides/main.html
docs/overrides/partials/tabs-item.html
mkdocs.yml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1212] Fix banner and latest redirect

---

docs/js/version-select.js
mkdocs.yml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1212][APPEND]  Fix version selector and banner query

---

python/hsfs/client/external.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1350] Add method to configure Databricks certificates on the fly

---

python/hsfs/embedding.py
python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1226] Make sure the index mapping limit does not exceed when creating feature group

---

python/hsfs/core/feature_group_api.py
python/hsfs/engine/python.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py
python/tests/test_feature_store.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1324][APPEND] Add fail safe in case feature_store property not set on feature group objects

---

python/hsfs/core/feature_descriptive_statistics.py
python/hsfs/core/feature_group_base_engine.py
python/hsfs/engine/python.py
python/hsfs/engine/spark.py
python/hsfs/feature.py
python/hsfs/feature_group.py
python/hsfs/feature_view.py
python/hsfs/training_dataset.py
python/hsfs/training_dataset_feature.py
python/hsfs/util.py
python/tests/core/test_feature_group_engine.py
python/tests/engine/test_python.py
python/tests/engine/test_spark.py
python/tests/fixtures/dataframe_fixtures.py
python/tests/test_feature.py
python/tests/test_feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1330] Autofix feature names which contains spaces

---

python/hsfs/core/opensearch.py
python/hsfs/core/vector_db_client.py
python/hsfs/embedding.py
python/hsfs/feature_group.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1317] Add retry and count to embedding index

---

python/hsfs/usage.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1359] Send datetime as utc in usage reports and add timezone + remove localhost testing

---

python/hsfs/engine/python.py
python/tests/engine/test_python.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1362] Fix profiling for null-only columns

---

python/hsfs/core/online_store_sql_client.py
python/hsfs/core/statistics_api.py
python/hsfs/core/transformation_function_engine.py
python/hsfs/core/vector_db_client.py
python/hsfs/core/vector_server.py
python/hsfs/feature_view.py
python/hsfs/statistics.py
python/hsfs/training_dataset.py
python/hsfs/util.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1333][APPEND] Several fixes for missing attributes or methods

---

.gitignore
python/hsfs/core/arrow_flight_client.py
python/hsfs/core/online_store_sql_client.py
python/hsfs/core/vector_db_client.py
python/hsfs/core/vector_server.py
python/hsfs/feature_view.py
python/hsfs/training_dataset.py
python/hsfs/util.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1333][APPEND] Add fixes for missing properties and method on vector server, feature view, vectorDbClient and online store sql client

---

python/hsfs/constructor/query.py
python/hsfs/core/arrow_flight_client.py
python/hsfs/core/feature_view_engine.py
python/hsfs/core/variable_api.py
python/hsfs/engine/python.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py
python/hsfs/feature_view.py
python/tests/core/test_arrow_flight_client.py
python/tests/core/test_feature_view_engine.py
python/tests/engine/test_python_reader.py

…ient
JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1331] Do not disable Hopsworks Feature Query Service on retryable failure

---

python/hsfs/constructor/query.py
python/hsfs/core/arrow_flight_client.py
python/hsfs/core/feature_view_engine.py
python/hsfs/core/variable_api.py
python/hsfs/engine/python.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py
python/hsfs/feature_view.py
python/tests/core/test_arrow_flight_client.py
python/tests/core/test_feature_view_engine.py
python/tests/engine/test_python_reader.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1331] Do not disable offline query service on failure, increase timeout and retry

---

python/hsfs/core/arrow_flight_client.py

Fix the cherry-picking of arrow_flight retries

[FSTORE-1331][APPEND] Fix timeout typo and cleanup static properties

---

java/beam/pom.xml
java/flink/pom.xml
java/hsfs/pom.xml
java/pom.xml
java/spark/pom.xml
python/hsfs/core/feature_group_api.py
python/hsfs/feature_group.py
python/hsfs/usage.py
python/hsfs/version.py
python/tests/core/test_feature_group_api.py
python/tests/fixtures/backend_fixtures.py
python/tests/fixtures/spine_group_fixtures.json
utils/java/pom.xml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1360][APPEND] fix get for cached and ondemand fgs

---

python/hsfs/core/feature_group_api.py
python/hsfs/feature_group.py
python/hsfs/usage.py
python/tests/core/test_feature_group_api.py
python/tests/fixtures/backend_fixtures.py
python/tests/fixtures/spine_group_fixtures.json

JIRA Issue: -
Related PRs: -
```
```

 [FSTORE-1360][APPEND] fix get for cached and ondemand fgs

---

python/hsfs/engine/spark.py
python/setup.py
python/tests/engine/test_spark.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1349] Cherry-pick great expectations upgrade to 3.7

---

python/hsfs/core/feature_group_api.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1360][append] Remove wild print

---

python/hsfs/core/vector_db_client.py
python/hsfs/feature_group.py
python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[APPEND][FSTORE-1226] Fix mapping in vector db client

---

python/pyproject.toml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1371] Add submodules and fix required python version

---

docs/templates/api/links.md

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1104][APPEND] Explicit storage connector provenance documentation

---

python/hsfs/core/online_store_sql_client.py
python/hsfs/core/vector_server.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1333][APPEND] fg_label and helper fix

---

docs/js/version-select.js
overrides/main.html
python/hsfs/feature_store.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1212] Add banner with redirect link to latest

---

python/hsfs/constructor/query.py
python/hsfs/core/feature_group_base_engine.py
python/hsfs/core/vector_db_client.py
python/hsfs/engine/python.py
python/hsfs/engine/spark.py
python/hsfs/feature_group.py
python/hsfs/storage_connector.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1261] Should be able to read vector store for embedding fg

---

python/hsfs/core/opensearch.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1378] Refactor opensearch client error handling

---

.gitignore
python/hsfs/constructor/prepared_statement_parameter.py
python/hsfs/constructor/serving_prepared_statement.py
python/hsfs/core/online_store_sql_client.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1398] Repr for sql statements + fix get_feature_vectors for label FG

---

python/hsfs/engine/python.py
python/tests/engine/test_python.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1402] skip_offsets logic is inverted

---

python/hsfs/core/vector_server.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1348][APPEND] enable default to sql client for none value

---

python/hsfs/core/feature_group_api.py
python/hsfs/core/online_store_rest_client_engine.py
python/hsfs/core/vector_server.py
python/hsfs/feature_store.py
python/hsfs/feature_view.py
python/hsfs/training_dataset.py
python/hsfs/util.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1415] Add helper column support for Online Store REST client

---

README.md
python/hsfs/__init__.py
python/hsfs/usage.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1414] Create a method for collecting client info

---

python/hsfs/client/online_store_rest_client.py
python/hsfs/core/online_store_rest_client_engine.py
python/hsfs/core/vector_server.py
python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1348][APPEND] If a feature is a label, then no need to fail if missing on pre-check

---

python/hsfs/core/vector_db_client.py
python/hsfs/feature_group.py
python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1417] Remove not implemented similarity search functionality from 3.8

---

auto_doc.py
docs/templates/api/embedding_feature_api.md
docs/templates/api/embedding_index_api.md
docs/templates/api/similarity_function_type_api.md
mkdocs.yml
python/hsfs/embedding.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1290] Add embedding classes to API reference 3.7

---

java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/hudi/DeltaStreamerKafkaSource.java
java/spark/src/main/java/com/logicalclocks/hsfs/spark/engine/hudi/HudiEngine.java

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1402-2][APPEND] Set FG id as kafka consumer group id for DeltaStreamer

---

python/hsfs/client/exceptions.py
python/hsfs/core/online_store_sql_engine.py
python/hsfs/core/vector_server.py
python/hsfs/feature_view.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1348] Key validation fixes

---

Dockerfile
Jenkinsfile

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1309] Switch to -m build to build the Python wheel

---

python/pyproject.toml

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1425] Publish hopsworks aiomysql fork on pypi

---

java/hsfs/src/main/java/com/logicalclocks/hsfs/metadata/HopsworksInternalClient.java

JIRA Issue: -
Related PRs: -
```
```

[HWORKS-1373] Append MATERIAL_DIRECTORY env var value to certificates path

---

python/hsfs/core/constants.py
python/hsfs/core/online_store_rest_client_api.py
python/hsfs/core/online_store_sql_engine.py
python/hsfs/core/util_sql.py
python/hsfs/engine/python.py
python/hsfs/util.py
python/tests/engine/test_python.py
python/tests/test_util.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1463] Refactor SQL dependencies out of util

---

python/.pre-commit-config.yaml
python/hsfs/connection.py
python/hsfs/constructor/query.py
python/hsfs/core/arrow_flight_client.py
python/hsfs/engine/__init__.py
python/hsfs/engine/python.py
python/hsfs/engine/spark_no_metastore.py
python/hsfs/feature_group.py
python/hsfs/feature_store.py
python/hsfs/feature_view.py
python/hsfs/util.py
python/pyproject.toml
python/tests/core/test_arrow_flight_client.py
python/tests/engine/test_python.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1462] Remove hive connection from python client

---

python/hsfs/engine/python.py

JIRA Issue: -
Related PRs: -
```
```

[FSTORE-1461][APPEND] Fix mistype of _project_id in engine/python

---

python/hsfs/engine/spark.py

JIRA Issue: -
Related PRs: -
```
```

[APPEND][FSTORE-1424] Feature logging fix _apply_transformation_function in spark
